const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');
const axios = require('axios');

dotenv.config();

const GOOGLE_SCRIPT_URL = process.env.GOOGLE_SCRIPT_URL;
if (!GOOGLE_SCRIPT_URL) {
    console.error("❌ CRITICAL: GOOGLE_SCRIPT_URL is not defined in .env!");
} else {
    console.log("✅ Email Bridge Configured:", GOOGLE_SCRIPT_URL.substring(0, 40) + "...");
}

// --- EMAIL CONFIGURATION (VIA GOOGLE SCRIPT BRIDGE) ---
async function sendOrderEmails(order, stockist) {
    
    try {
        const itemRows = order.items.map(item => `
            <tr>
                <td style="padding:8px; border-bottom:1px solid #eee;">${item.name}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:center;">${item.qty}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:center;">${item.bonusQty || 0}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:right;">₹${item.totalValue.toFixed(2)}</td>
            </tr>
        `).join('');

        const emailBody = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background: #fff;">
                <div style="background: #6366f1; color: white; padding: 20px; text-align: center;">
                    <h2 style="margin: 0;">New Order Alert: ${order.orderNo}</h2>
                </div>
                <div style="padding: 20px; color: #1e293b;">
                    <p><strong>Stockist:</strong> ${stockist.name}</p>
                    <p><strong>City/Address:</strong> ${stockist.address || 'N/A'}</p>
                    <p><strong>Phone:</strong> ${stockist.phone || 'N/A'}</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <table style="width: 100%; border-collapse: collapse;">
                        <thead>
                            <tr style="background: #f8fafc;">
                                <th style="text-align:left; padding:8px;">Product</th>
                                <th style="padding:8px;">Qty</th>
                                <th style="padding:8px;">Bonus</th>
                                <th style="text-align:right; padding:8px;">Value</th>
                            </tr>
                        </thead>
                        <tbody>${itemRows}</tbody>
                    </table>
                    <div style="margin-top: 20px; text-align: right; border-top: 2px solid #6366f1; padding-top: 10px;">
                        <p style="margin: 5px 0;"><strong>Subtotal:</strong> ₹${order.subTotal.toFixed(2)}</p>
                        <p style="margin: 5px 0;"><strong>GST Amount:</strong> ₹${order.gstAmount.toFixed(2)}</p>
                        <p style="margin: 5px 0; font-size: 1.25rem; color: #6366f1;"><strong>Grand Total:</strong> ₹${order.grandTotal.toFixed(2)}</p>
                    </div>
                </div>
                <div style="background: #f8fafc; padding: 15px; font-size: 0.8rem; color: #64748b; text-align: center;">
                    Generated by EMYRIS OMS Portal
                </div>
            </div>
        `;

        const recipients = `emyrisbio@gmail.com, ${process.env.SUPER_DISTRIBUTOR_EMAIL || 'emyrisbio@gmail.com'}`;
        
        await sendEmail(recipients, `📦 Order Received: ${order.orderNo} [${stockist.name}]`, emailBody);

        console.log(`✅ Bridge Email Success: ${order.orderNo}`);
    } catch (e) { console.error("❌ Bridge Email Fail:", e.message); }
}

async function sendEmail(to, subject, html) {
    if (!GOOGLE_SCRIPT_URL) {
        console.warn("⚠️ No GOOGLE_SCRIPT_URL configured. Email not sent to:", to);
        return false;
    }
    try {
        console.log(`📤 Attempting email to: ${to} | Subject: ${subject}`);
        const res = await axios.post(GOOGLE_SCRIPT_URL, { to, subject, html }, { timeout: 15000 });
        if (res.data && res.data.status === 'success') {
            console.log(`✅ Email Sent Successfully to: ${to}`);
            return true;
        } else {
            console.error(`❌ Bridge returned error for ${to}:`, res.data);
            return false;
        }
    } catch (e) {
        console.error(`❌ Email failed for ${to}:`, e.message);
        if (e.code === 'ECONNABORTED') console.error("   Reason: Request timed out (15s)");
        return false;
    }
}

const dns = require('dns');
// Force Google DNS for SRV resolution (fixes connection issues on some networks)
try {
    dns.setServers(['8.8.8.8', '8.8.4.4']);
    console.log('🌐 [DNS] Switched to Google DNS for Atlas connection');
} catch (e) {
    console.warn('⚠️ [DNS] Failed to set custom DNS servers:', e.message);
}

const app = express();
// DB Stats
app.get('/api/admin/db-stats', async (req, res) => {
    try {
        const stats = await mongoose.connection.db.command({ dbStats: 1 });
        // MongoDB Atlas free tier is 512MB
        const capacityMB = 512;
        const usedMB = (stats.dataSize + stats.indexSize) / (1024 * 1024);
        res.json({
            usedMB: usedMB.toFixed(2),
            capacityMB,
            percent: ((usedMB / capacityMB) * 100).toFixed(1)
        });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());
app.use(express.static(__dirname));

// MongoDB Connection
const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/emyris-oms";
mongoose.connect(MONGODB_URI)
    .then(() => console.log('✅ EMYRIS-OMS Database Connected'))
    .catch(err => console.error('❌ Database Connection Error:', err));

// --- SCHEMAS ---

// 1. Company Profile
const companySchema = new mongoose.Schema({
    name: { type: String, default: "EMYRIS BIOLIFESCIENCES" },
    address: { type: String, default: "Your Office Address Here" },
    websites: { type: [String], default: ["www.emyrisbio.com", "www.emyris.in"] },
    phones: { type: [String], default: ["+91-XXXXXXXXXX"] },
    tollFree: { type: String, default: "7993163300" },
    emails: { type: [String], default: ["contact@emyrisbio.com", "sales@emyrisbio.com", "support@emyrisbio.com"] },
    superDistributorEmail: String,
    adminEmail: String,
    gstRate: { type: Number, default: 12 },
    scrollingMessage: {
        text: { type: String, default: "Welcome to EMYRIS OMS Portal - Your partner in healthcare." },
        color: { type: String, default: "#6366f1" },
        speed: { type: Number, default: 30 }
    }
});

// 2. Global Masters
const categorySchema = new mongoose.Schema({ name: { type: String, required: true, unique: true } });
const groupSchema = new mongoose.Schema({ name: { type: String, required: true, unique: true } });
const hsnSchema = new mongoose.Schema({ code: { type: String, required: true, unique: true }, description: String });
const gstSchema = new mongoose.Schema({ rate: { type: Number, required: true, unique: true } });

// 2. Product Master
const productSchema = new mongoose.Schema({
    name: { type: String, required: true },
    hsn: String,
    category: { type: String, default: "GENERAL" },
    group: { type: String, default: "GENERAL" },
    packing: String,
    mrp: { type: Number, default: 0 },
    ptr: { type: Number, default: 0 }, // Price to Retailer
    pts: { type: Number, default: 0 }, // Price to Stockist
    gstPercent: { type: Number, default: 12 },
    qtyAvailable: { type: Number, default: 0 },
    bonusScheme: {
        buy: { type: Number, default: 0 },
        get: { type: Number, default: 0 }
    },
    active: { type: Boolean, default: true }
});

// 3. Stockist / Distributor
const stockistSchema = new mongoose.Schema({
    name: { type: String, required: true },
    loginId: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    address: String,
    phone: String,
    email: String,
    dlNo: String,
    gstNo: String,
    fssaiNo: String,
    panNo: { type: String, required: true },
    approved: { type: Boolean, default: false },
    negotiatedPrices: [{
        productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        lockedRate: Number,
        expiryDate: Date,
        note: String
    }],
    stockistCode: String,
    loginPin: String,
    registeredAt: { type: Date, default: Date.now }
});

// 4. Order
const orderSchema = new mongoose.Schema({
    orderNo: { type: String, unique: true },
    stockist: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist' },
    stockistCode: String,
    items: [{
        product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        qty: Number,
        bonusQty: { type: Number, default: 0 },
        priceUsed: Number,
        askingRate: Number,
        masterRate: Number,
        negotiationNote: String,
        totalValue: Number
    }],
    subTotal: Number,
    gstAmount: Number,
    grandTotal: Number,
    status: { type: String, default: 'pending' },
    bonusApproval: {
        isManual: { type: Boolean, default: false },
        approvedBy: String,
        approvedAt: Date
    },
    createdAt: { type: Date, default: Date.now }
});

const Company = mongoose.model('Company', companySchema);
const Product = mongoose.model('Product', productSchema);
const Stockist = mongoose.model('Stockist', stockistSchema);
const Order = mongoose.model('Order', orderSchema);
const Category = mongoose.model('Category', categorySchema);
const Group = mongoose.model('Group', groupSchema);
const HSN = mongoose.model('HSN', hsnSchema);
const GST = mongoose.model('GST', gstSchema);

// --- NEGOTIATION ENDPOINTS ---

app.put('/api/admin/orders/:orderId/items/:itemId/negotiate', async (req, res) => {
    const { action } = req.body;
    try {
        const order = await Order.findById(req.params.orderId);
        if (!order) return res.status(404).json({ success: false, message: "Order not found" });

        const item = order.items.id(req.params.itemId);
        if (!item) return res.status(404).json({ success: false, message: "Item not found" });

        const { customRate } = req.body;
        const finalRate = customRate !== undefined ? Number(customRate) : (item.askingRate || item.priceUsed);

        if (action === 'reject') {
            item.priceUsed = item.masterRate;
            item.askingRate = undefined;
        } else if (action === 'onetime') {
            item.priceUsed = finalRate;
        } else {
            item.priceUsed = finalRate;
            let expiry = new Date();
            if (action === 'month') expiry.setMonth(expiry.getMonth() + 1);
            if (action === 'year') expiry.setFullYear(expiry.getFullYear() + 1);

            await Stockist.findByIdAndUpdate(order.stockist, {
                $pull: { negotiatedPrices: { productId: item.product } }
            });
            await Stockist.findByIdAndUpdate(order.stockist, {
                $push: { negotiatedPrices: {
                    productId: item.product,
                    lockedRate: item.priceUsed,
                    expiryDate: expiry,
                    note: item.negotiationNote
                }}
            });
        }

        order.subTotal = order.items.reduce((acc, curr) => acc + (curr.priceUsed * curr.qty), 0);
        order.gstAmount = order.subTotal * 0.12; 
        order.grandTotal = order.subTotal + order.gstAmount;

        await order.save();
        res.json({ success: true, order });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// --- API ENDPOINTS ---

app.get('/api/health', (req, res) => res.json({ status: 'running', database: mongoose.connection.readyState === 1 }));

// Auth & Registration
app.post('/api/stockist/register', async (req, res) => {
    try {
        const { name, password, address, phone, email, dlNo, gstNo, fssaiNo, panNo } = req.body;
        
        // Auto-generate Login ID (EMY + Random 6 Digits)
        let loginId;
        let isUnique = false;
        while (!isUnique) {
            loginId = 'EMY' + Math.floor(100000 + Math.random() * 900000);
            const existing = await Stockist.findOne({ loginId });
            if (!existing) isUnique = true;
        }

        const newStockist = new Stockist({ name, loginId, password, address, phone, email, dlNo, gstNo, fssaiNo, panNo });
        await newStockist.save();
        console.log(`👤 DB: New Stockist saved -> ${name}`);

        // 1. Send Registration Confirmation to Stockist
        const welcomeEmail = `
            <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background-color: #f1f5f9;">
                <div style="background-color: #ffffff; padding: 40px; border-radius: 24px; max-width: 500px; margin: 0 auto; border: 1px solid #e2e8f0;">
                    <h2 style="color: #6366f1; margin-top: 0;">Registration Received!</h2>
                    <p>Hello <strong>${name}</strong>,</p>
                    <p>Thank you for registering with the EMYRIS Distribution Network. Your application is currently under review by our administration team.</p>
                    <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #e2e8f0;">
                        <p style="margin: 0; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase;">Status</p>
                        <p style="margin: 5px 0 0 0; font-size: 18px; font-weight: 800; color: #f59e0b;">APPROVAL PENDING</p>
                    </div>
                    <p style="font-size: 14px; color: #64748b;">Once your Drug License and compliance data are verified, you will receive another email with your activation details.</p>
                </div>
            </div>
        `;
        console.log(`📧 Sending welcome email to: ${email}`);
        await sendEmail(email, "📦 EMYRIS Registration Received - Approval Pending", welcomeEmail);

        // 2. Send Admin Notification to emyrisbio@gmail.com
        const adminNotifyEmail = `
            <div style="font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 30px; background-color: #f8fafc;">
                <div style="background-color: #ffffff; padding: 40px; border-radius: 24px; border: 1px solid #e2e8f0; max-width: 600px; margin: 0 auto; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);">
                    <h2 style="color: #6366f1; margin-top: 0; font-size: 20px;">🔔 New Stockist Registration</h2>
                    <p style="color: #64748b; font-size: 14px;">A new application has been submitted for the EMYRIS Distribution Network.</p>
                    
                    <div style="background: #f1f5f9; padding: 25px; border-radius: 16px; margin: 25px 0; border: 1px solid #e2e8f0;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 14px; color: #1e293b;">
                            <tr><td style="padding: 8px 0; color: #64748b;">Firm Name:</td><td style="padding: 8px 0; font-weight: 700; text-transform: uppercase;">${name}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">Phone:</td><td style="padding: 8px 0; font-weight: 700;">${phone}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">Email:</td><td style="padding: 8px 0; font-weight: 700;">${email}</td></tr>
                            <tr><td colspan="2"><hr style="border: 0; border-top: 1px solid #cbd5e1; margin: 10px 0;"></td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">GSTIN:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${gstNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">PAN:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${panNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">DL No:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${dlNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">FSSAI:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${fssaiNo}</td></tr>
                        </table>
                    </div>
                    
                    <p style="font-size: 14px; color: #475569;">Please log in to the <strong>Admin Command Center</strong> to verify compliance documents and approve this registration.</p>
                    <div style="text-align: center; margin-top: 30px;">
                        <a href="${process.env.PORTAL_URL || 'https://emyris-oms.onrender.com'}/admin.html" style="background-color: #6366f1; color: #ffffff; padding: 12px 24px; border-radius: 12px; text-decoration: none; font-weight: 700; font-size: 14px;">OPEN ADMIN DASHBOARD</a>
                    </div>
                </div>
            </div>
        `;
        console.log(`📧 Sending admin notification to: emyrisbio@gmail.com`);
        await sendEmail("emyrisbio@gmail.com", "🔔 New Stockist Registration: " + name, adminNotifyEmail);

        res.json({ success: true, message: `Registration successful! Please wait for Admin approval. Your ID will be sent to ${email} once approved.` });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/login', async (req, res) => {
    let { loginId, password } = req.body;
    try {
        if (!loginId || !password) return res.status(400).json({ success: false, message: 'ID and Password are required' });
        
        // Case-insensitive ID lookup
        const user = await Stockist.findOne({ 
            loginId: { $regex: new RegExp(`^${loginId.trim()}$`, 'i') }, 
            password: password.trim() 
        });

        if (!user) return res.status(401).json({ success: false, message: 'Invalid Credentials' });
        if (!user.approved) return res.status(403).json({ success: false, message: 'Account pending approval' });
        
        // Generate 6-digit PIN
        const pin = Math.floor(100000 + Math.random() * 900000).toString();
        user.loginPin = pin;
        await user.save();

        // Send PIN Email
        const pinEmail = `
            <div style="font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 40px; background: #0f172a; color: #fff; text-align: center;">
                <div style="background: rgba(255,255,255,0.05); padding: 40px; border-radius: 24px; border: 1px solid rgba(255,255,255,0.1); max-width: 400px; margin: 0 auto;">
                    <h2 style="color: #6366f1; margin-bottom: 10px;">Security Verification</h2>
                    <p style="color: #94a3b8; font-size: 14px; margin-bottom: 30px;">Use the code below to complete your login</p>
                    <div style="font-size: 3rem; font-weight: 900; letter-spacing: 10px; color: #fff; margin-bottom: 30px; background: rgba(99, 102, 241, 0.1); padding: 20px; border-radius: 12px; border: 1px dashed #6366f1;">
                        ${pin}
                    </div>
                    <p style="font-size: 12px; color: #64748b;">This code will expire shortly. Do not share this PIN with anyone.</p>
                </div>
            </div>
        `;
        
        await sendEmail(user.email, "🔐 EMYRIS Security PIN: " + pin, pinEmail);
        console.log(`[LOGIN] PIN Sent to ${user.email} for ${loginId}`);
        
        res.json({ success: true, message: 'PIN sent to your registered email' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/verify-login-pin', async (req, res) => {
    const { loginId, pin } = req.body;
    try {
        const user = await Stockist.findOne({ loginId, loginPin: pin });
        if (!user) return res.status(401).json({ success: false, message: 'Invalid or expired PIN' });
        
        user.loginPin = undefined; // Clear pin
        await user.save();
        console.log(`[PIN] Verified for ${loginId}`);
        res.json({ success: true, user });
    } catch (err) { console.error("[PIN] Error:", err.message); res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/forgot-id-pw', async (req, res) => {
    let { email } = req.body;
    try {
        if (!email) return res.status(400).json({ success: false, message: 'Email is required' });
        email = email.trim().toLowerCase();
        
        console.log(`[RECOVERY] Searching for: "${email}"`);
        const user = await Stockist.findOne({ email: { $regex: new RegExp(`^${email}$`, 'i') } });
        
        if (!user) {
            console.warn(`[RECOVERY] No user found for: ${email}`);
            return res.status(404).json({ success: false, message: 'No account found with this email address.' });
        }

        const emailContent = `
            <div style="font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 40px; background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); color: #f1f5f9;">
                <div style="background: rgba(30, 41, 59, 0.7); padding: 50px; border-radius: 32px; border: 1px solid rgba(255, 255, 255, 0.1); max-width: 500px; margin: 0 auto; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);">
                    <div style="text-align: center; margin-bottom: 40px;">
                        <h1 style="color: #6366f1; margin: 0; font-size: 28px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase;">EMYRIS BIOLIFESCIENCES</h1>
                        <p style="color: #94a3b8; font-size: 14px; margin-top: 8px; font-weight: 600; letter-spacing: 1px;">SECURE CREDENTIALS RECOVERY</p>
                    </div>
                    
                    <p style="font-size: 16px; line-height: 1.6; color: #cbd5e1;">Hello <strong>${user.name}</strong>,</p>
                    <p style="font-size: 15px; line-height: 1.6; color: #94a3b8;">We received a request to retrieve your account credentials. Please use the details below to securely access your portal:</p>
                    
                    <div style="background: rgba(15, 23, 42, 0.6); padding: 35px; border-radius: 24px; margin: 35px 0; border: 1px solid rgba(255, 255, 255, 0.05); text-align: center;">
                        <div style="margin-bottom: 25px;">
                            <label style="display: block; color: #6366f1; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Login ID</label>
                            <span style="font-family: 'Courier New', monospace; color: #fff; font-size: 24px; font-weight: 800; letter-spacing: 1px;">${user.loginId}</span>
                        </div>
                        <div>
                            <label style="display: block; color: #6366f1; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Password</label>
                            <span style="font-family: 'Courier New', monospace; color: #fff; font-size: 24px; font-weight: 800; letter-spacing: 1px;">${user.password}</span>
                        </div>
                    </div>
                    
                    <div style="text-align: center; margin-top: 40px;">
                        <p style="font-size: 12px; color: #64748b; font-weight: 500;">If you did not request this, please contact support immediately.</p>
                        <hr style="border: 0; border-top: 1px solid rgba(255, 255, 255, 0.05); margin: 25px 0;">
                        <p style="font-size: 11px; color: #475569;">&copy; 2026 EMYRIS OMS • ADVANCED DISTRIBUTION SYSTEM</p>
                    </div>
                </div>
            </div>
        `;
        
        await sendEmail(user.email, "📦 Account Credentials Recovery", emailContent);
        res.json({ success: true, message: 'Login details have been sent to your email.' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Login
app.post('/api/admin/login', (req, res) => {
    const { adminId, password } = req.body;
    const correctId = process.env.ADMIN_ID || "EMYRIS";
    const correctPass = process.env.ADMIN_PASSWORD || "1234";

    console.log(`[DEBUG] Login attempt - ID: "${adminId}" (${adminId.length}), Pass: "${password}" (${password.length})`);
    console.log(`[DEBUG] Correct - ID: "${correctId}" (${correctId.length}), Pass: "${correctPass}" (${correctPass.length})`);

    if (adminId.trim() === correctId.trim() && password.trim() === correctPass.trim()) {
        res.json({ success: true });
    } else {
        res.status(401).json({ success: false, message: 'Invalid Admin Credentials' });
    }
});

// Admin: Bulk Add Products
app.post('/api/admin/products/bulk', async (req, res) => {
    try {
        const { products } = req.body;
        if (!Array.isArray(products)) return res.status(400).json({ success: false, message: 'Invalid data' });
        const results = { success: 0, failed: 0, errors: [] };
        for (const p of products) {
            try {
                if (!p.name) { results.failed++; results.errors.push("Missing Product Name"); continue; }
                const newProd = new Product({
                    name: p.name,
                    hsn: p.hsn,
                    category: p.category || "GENERAL",
                    mrp: Number(p.mrp) || 0,
                    ptr: Number(p.ptr) || 0,
                    pts: Number(p.pts) || 0,
                    gstPercent: Number(p.gstPercent) || 12,
                    qtyAvailable: Number(p.qtyAvailable) || 0,
                    bonusScheme: { buy: Number(p.buy) || 0, get: Number(p.get) || 0 }
                });
                await newProd.save();
                results.success++;
            } catch (e) {
                results.failed++;
                results.errors.push(`${p.name || 'Unknown'}: ${e.message}`);
            }
        }
        res.json({ success: true, results });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Single Add Product
app.post('/api/admin/products', async (req, res) => {
    try {
        console.log("[DEBUG] Adding Product:", req.body);
        const newProd = new Product(req.body);
        await newProd.save();
        res.json({ success: true, product: newProd });
    } catch (err) { 
        console.error('❌ Product Save Error:', err.message);
        res.status(500).json({ success: false, error: err.message }); 
    }
});

// Admin: Update Product
app.put('/api/admin/products/:id', async (req, res) => {
    try {
        const product = await Product.findByIdAndUpdate(req.params.id, req.body, { new: true });
        if (!product) return res.status(404).json({ success: false, message: 'Product not found' });
        res.json({ success: true, product });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Delete Product
app.delete('/api/admin/products/:id', async (req, res) => {
    try {
        const product = await Product.findByIdAndDelete(req.params.id);
        if (!product) return res.status(404).json({ success: false, message: 'Product not found' });
        res.json({ success: true });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Get All Stockists
app.get('/api/admin/stockists', async (req, res) => {
    try {
        const stockists = await Stockist.find().sort({ registeredAt: -1 });
        res.json(stockists);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Delete Individual Stockist
app.delete('/api/admin/stockists/:id', async (req, res) => {
    try {
        await Stockist.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Stockist deleted' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Master Delete All Stockists (Wipes only Stockists)
app.delete('/api/admin/stockists-bulk/all', async (req, res) => {
    try {
        const result = await Stockist.deleteMany({});
        res.json({ success: true, message: `${result.deletedCount} Stockists deleted.` });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Approve Stockist
app.put('/api/admin/stockists/:id/approve', async (req, res) => {
    try {
        const sid = req.params.id;
        console.log(`[ADMIN] Approving stockist: ${sid}`);

        // Update Stockist Status
        const stockist = await Stockist.findByIdAndUpdate(sid, { 
            approved: true
        }, { new: true });

        if (!stockist) {
            console.error(`❌ [ADMIN] Stockist ${sid} not found`);
            return res.status(404).json({ success: false, message: 'Stockist not found' });
        }

        console.log(`✅ [ADMIN] Approved: ${stockist.name}`);

        // 4. Send Confirmation Email
        const emailContent = `
            <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; max-width: 500px; background-color: #ffffff;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h2 style="color: #10b981; margin: 0;">Account Approved!</h2>
                    <p style="color: #64748b; font-size: 14px;">EMYRIS BIOLIFESCIENCES</p>
                </div>
                
                <p>Hello <strong>${stockist.name}</strong>,</p>
                <p>Your account has been verified and successfully approved by the EMYRIS Admin team.</p>
                
                <div style="background: #f0fdf4; padding: 25px; border-radius: 16px; margin: 25px 0; border: 1px solid #bbf7d0; text-align: center;">
                    <p style="margin: 0 0 10px 0; color: #166534; font-size: 0.8rem; font-weight: 700; text-transform: uppercase;">Your Portal Credentials</p>
                    <div style="margin-bottom: 15px;">
                        <span style="color: #64748b; font-size: 13px;">Login ID:</span><br>
                        <strong style="font-family: monospace; font-size: 1.2rem; color: #10b981;">${stockist.loginId}</strong>
                    </div>
                    <div>
                        <span style="color: #64748b; font-size: 13px;">Password:</span><br>
                        <strong style="font-family: monospace; font-size: 1.2rem; color: #10b981;">${stockist.password}</strong>
                    </div>
                </div>
                
                <p>Access the portal here: <a href="${process.env.PORTAL_URL || 'https://emyris-oms.onrender.com'}" style="color: #6366f1; font-weight: 700; text-decoration: none;">Stockist Portal</a></p>
                
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 0.8rem; color: #64748b; text-align: center;">Welcome to the EMYRIS network. We look forward to a successful partnership.</p>
            </div>
        `;
        await sendEmail(stockist.email, "✅ EMYRIS Account Approved - Portal Access Active", emailContent);

        res.json({ success: true, stockist });
    } catch (err) { 
        console.error("❌ [ADMIN] Approval logic failed:", err.message);
        res.status(500).json({ error: err.message }); 
    }
});

// --- SETTINGS & MASTERS ---

app.get('/api/admin/settings', async (req, res) => {
    let settings = await Company.findOne();
    if (!settings) settings = await Company.create({});
    res.json(settings);
});

app.post('/api/admin/settings', async (req, res) => {
    try {
        let settings = await Company.findOne();
        if (!settings) settings = new Company(req.body);
        else Object.assign(settings, req.body);
        await settings.save();
        res.json({ success: true, settings });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// Category Master
app.get('/api/admin/categories', async (req, res) => res.json(await Category.find()));
app.post('/api/admin/categories', async (req, res) => {
    try {
        const cat = new Category(req.body);
        await cat.save();
        res.json({ success: true, category: cat });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/categories/:id', async (req, res) => {
    await Category.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// Group Master
app.get('/api/admin/groups', async (req, res) => res.json(await Group.find()));
app.post('/api/admin/groups', async (req, res) => {
    try {
        const grp = new Group(req.body);
        await grp.save();
        res.json({ success: true, group: grp });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/groups/:id', async (req, res) => {
    await Group.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// HSN Master
app.get('/api/admin/hsns', async (req, res) => res.json(await HSN.find()));
app.post('/api/admin/hsns', async (req, res) => {
    try {
        const hsn = new HSN(req.body);
        await hsn.save();
        res.json({ success: true, hsn });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/hsns/:id', async (req, res) => {
    await HSN.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// GST Master
app.get('/api/admin/gst', async (req, res) => res.json(await GST.find()));
app.post('/api/admin/gst', async (req, res) => {
    try {
        const gst = new GST(req.body);
        await gst.save();
        res.json({ success: true, gst });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/gst/:id', async (req, res) => {
    await GST.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// Public Products List
app.get('/api/products', async (req, res) => {
    try {
        const products = await Product.find({ active: true });
        res.json(products);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Orders
app.post('/api/orders/create', async (req, res) => {
    try {
        const { stockistId, stockistCode, items, subTotal, gstAmount, grandTotal } = req.body;
        
        // Generate Order No (EMY-ORD-YYYYMMDD-XXXX)
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await Order.countDocuments();
        const orderNo = `EMY-ORD-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        const newOrder = new Order({
            orderNo,
            stockist: stockistId,
            stockistCode,
            items,
            subTotal,
            gstAmount,
            grandTotal
        });
        await newOrder.save();

        // Fetch stockist details for the email
        const stockist = await Stockist.findById(stockistId);
        if (stockist) {
            sendOrderEmails(newOrder, stockist);
        }

        res.json({ success: true, order: newOrder });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/admin/orders', async (req, res) => {
    try {
        const orders = await Order.find().populate('stockist').sort({ createdAt: -1 });
        res.json(orders);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Stockist: Get My Orders
app.get('/api/orders/my-orders/:stockistId', async (req, res) => {
    try {
        const orders = await Order.find({ stockist: req.params.stockistId }).sort({ createdAt: -1 });
        res.json(orders);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Approve Order
app.put('/api/admin/orders/:id/approve', async (req, res) => {
    try {
        const { approvedBy } = req.body;
        const order = await Order.findByIdAndUpdate(req.params.id, {
            status: 'approved',
            'bonusApproval.approvedBy': approvedBy || 'ADMIN',
            'bonusApproval.approvedAt': new Date()
        }, { new: true });
        
// Admin: Reject Order
app.put('/api/admin/orders/:id/reject', async (req, res) => {
    try {
        const order = await Order.findByIdAndUpdate(req.params.id, {
            status: 'rejected'
        }, { new: true });
        res.json({ success: true, order });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Delete Order
app.delete('/api/admin/orders/:id', async (req, res) => {
    try {
        await Order.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Order deleted' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.listen(PORT, () => console.log(`🚀 OMS Server running on http://localhost:${PORT}`));
