const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');
const axios = require('axios');
const path = require('path');
const fs = require('fs');
const multer = require('multer');

dotenv.config();
const cloudinary = require('cloudinary').v2;

// Cloudinary Configuration
cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET
});


// Ensure uploads folder exists
const uploadDir = path.join(__dirname, 'uploads', 'media');
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

// Multer Storage Configuration
const storage = multer.diskStorage({
    destination: (req, file, cb) => cb(null, uploadDir),
    filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname)
});
const upload = multer({ 
    storage,
    fileFilter: (req, file, cb) => {
        const allowedTypes = ['audio/mpeg', 'video/mp4', 'audio/mp3'];
        if (allowedTypes.includes(file.mimetype)) cb(null, true);
        else cb(new Error('Invalid file type. Only MP3 and MP4 allowed.'));
    }
});


const GOOGLE_SCRIPT_URL = process.env.GOOGLE_SCRIPT_URL;
if (!GOOGLE_SCRIPT_URL) {
    console.error("❌ CRITICAL: GOOGLE_SCRIPT_URL is not defined in .env!");
} else {
    console.log("✅ Email Bridge Configured:", GOOGLE_SCRIPT_URL.substring(0, 40) + "...");
}

// --- EMAIL CONFIGURATION (VIA GOOGLE SCRIPT BRIDGE) ---
async function sendOrderEmails(order, stockist) {
    
    try {
        const itemRows = order.items.map(item => `
            <tr>
                <td style="padding:8px; border-bottom:1px solid #eee;">${item.name}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:center;">${item.qty}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:center;">${item.bonusQty || 0}</td>
                <td style="padding:8px; border-bottom:1px solid #eee; text-align:right;">₹${item.totalValue.toFixed(2)}</td>
            </tr>
        `).join('');

        const emailBody = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background: #fff;">
                <div style="background: #6366f1; color: white; padding: 20px; text-align: center;">
                    <h2 style="margin: 0;">New Order Alert: ${order.orderNo}</h2>
                </div>
                <div style="padding: 20px; color: #1e293b;">
                    <p><strong>Stockist:</strong> ${stockist.name}</p>
                    <p><strong>City/Address:</strong> ${stockist.address || 'N/A'}</p>
                    <p><strong>Phone:</strong> ${stockist.phone || 'N/A'}</p>
                    <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                    <table style="width: 100%; border-collapse: collapse;">
                        <thead>
                            <tr style="background: #f8fafc;">
                                <th style="text-align:left; padding:8px;">Product</th>
                                <th style="padding:8px;">Qty</th>
                                <th style="padding:8px;">Bonus</th>
                                <th style="text-align:right; padding:8px;">Value</th>
                            </tr>
                        </thead>
                        <tbody>${itemRows}</tbody>
                    </table>
                    <div style="margin-top: 20px; text-align: right; border-top: 2px solid #6366f1; padding-top: 10px;">
                        <p style="margin: 5px 0;"><strong>Subtotal:</strong> ₹${order.subTotal.toFixed(2)}</p>
                        <p style="margin: 5px 0;"><strong>GST Amount:</strong> ₹${order.gstAmount.toFixed(2)}</p>
                        <p style="margin: 5px 0; font-size: 1.25rem; color: #6366f1;"><strong>Grand Total:</strong> ₹${order.grandTotal.toFixed(2)}</p>
                    </div>
                </div>
                <div style="background: #f8fafc; padding: 15px; font-size: 0.8rem; color: #64748b; text-align: center;">
                    Generated by EMYRIS OMS Portal
                </div>
            </div>
        `;

        const recipients = `emyrisbio@gmail.com, ${process.env.SUPER_DISTRIBUTOR_EMAIL || 'emyrisbio@gmail.com'}`;
        
        await sendEmail(recipients, `📦 Order Received: ${order.orderNo} [${stockist.name}]`, emailBody);

        console.log(`✅ Bridge Email Success: ${order.orderNo}`);
    } catch (e) { console.error("❌ Bridge Email Fail:", e.message); }
}

async function sendEmail(to, subject, html, retryCount = 0) {
    if (!GOOGLE_SCRIPT_URL) {
        console.warn("⚠️ No GOOGLE_SCRIPT_URL configured. Email not sent to:", to);
        return false;
    }
    try {
        console.log(`📤 Attempting email (Attempt ${retryCount + 1}) to: ${to}`);
        const res = await axios.post(GOOGLE_SCRIPT_URL, { to, subject, html }, { timeout: 15000 });
        
        if (res.data && (res.data.status === 'success' || res.data.success === true)) {
            console.log(`✅ Email Sent Successfully to: ${to}`);
            return true;
        } else {
            throw new Error(res.data ? JSON.stringify(res.data) : "Unknown Bridge Error");
        }
    } catch (e) {
        console.error(`❌ Email attempt ${retryCount + 1} failed for ${to}:`, e.message);
        
        if (retryCount < 1) { // Retry once
            console.log(`🔄 Retrying email to ${to}...`);
            return await sendEmail(to, subject, html, retryCount + 1);
        } else {
            // Log to FailedEmails for manual recovery
            try {
                await FailedEmail.create({ to, subject, html, error: e.message, attempts: retryCount + 1 });
                console.log(`💾 Logged failed email to ${to} for recovery.`);
            } catch (logErr) { console.error("❌ Failed to log email error:", logErr.message); }
            return false;
        }
    }
}

const dns = require('dns');
// Force Google DNS for SRV resolution (fixes connection issues on some networks)
try {
    dns.setServers(['8.8.8.8', '8.8.4.4']);
    console.log('🌐 [DNS] Switched to Google DNS for Atlas connection');
} catch (e) {
    console.warn('⚠️ [DNS] Failed to set custom DNS servers:', e.message);
}

const app = express();
// --- CLOUD HEALTH CHECK ---
app.get('/health', (req, res) => res.status(200).json({ status: 'UP', timestamp: new Date() }));

// DB Stats
app.get('/api/admin/db-stats', async (req, res) => {
    try {
        if (mongoose.connection.readyState !== 1) throw new Error("Database not connected");
        const stats = await mongoose.connection.db.command({ dbStats: 1 });
        // MongoDB Atlas free tier is 512MB
        const capacityMB = 512;
        const usedMB = (stats.dataSize + stats.indexSize) / (1024 * 1024);
        res.json({
            usedMB: usedMB.toFixed(2),
            capacityMB,
            percent: ((usedMB / capacityMB) * 100).toFixed(1)
        });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());
app.use(express.static(__dirname));

// MongoDB Connection
const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
    console.warn('⚠️ WARNING: MONGODB_URI not found in environment. Deployment may fail.');
}

mongoose.connect(MONGODB_URI || "mongodb://127.0.0.1:27017/emyris-oms", {
    serverSelectionTimeoutMS: 10000 // 10s timeout to prevent hanging on Render
})
    .then(() => console.log('✅ EMYRIS-OMS Database Connected'))
    .catch(err => {
        console.error('❌ Database Connection Error:', err.message);
        console.log('💡 TIP: Ensure you have added MONGODB_URI in Render Environment Variables and whitelisted Render IP (0.0.0.0/0) in Atlas.');
    });

// --- SCHEMAS ---

// 1. Company Profile
const companySchema = new mongoose.Schema({
    name: { type: String, default: "EMYRIS BIOLIFESCIENCES" },
    address: { type: String, default: "Your Office Address Here" },
    websites: { type: [String], default: ["www.emyrisbio.com", "www.emyris.in"] },
    phones: { type: [String], default: ["+91-XXXXXXXXXX"] },
    tollFree: { type: String, default: "7993163300" },
    emails: { type: [String], default: ["contact@emyrisbio.com", "sales@emyrisbio.com", "support@emyrisbio.com"] },
    superDistributorEmail: String,
    adminEmail: String,
    gstRate: { type: Number, default: 12 },
    // Legal Compliance Details
    gstNo:   { type: String, default: "" },
    panNo:   { type: String, default: "" },
    dlNo:    { type: String, default: "" },
    fssaiNo: { type: String, default: "" },
    bankDetails: { type: String, default: "Bank Name: HDFC Bank\nA/C No: 123456789012\nIFSC Code: HDFC0001234" },
    termsConditions: { type: String, default: "1. Goods once sold will not be taken back.\n2. Interest @ 24% p.a. will be charged if payment is delayed." },
    signatureImage: { type: String, default: "" },
    logoImage: { type: String, default: "" },
    upiId: { type: String, default: "" },
    bankAccountNo: { type: String, default: "" },
    bankIfsc: { type: String, default: "" },
    // Multimedia
    musicUrl: { type: String, default: "" },
    videoUrl: { type: String, default: "" },
    musicVolume: { type: Number, default: 0.5 },

    // Document Specific Formats

    invoiceTerms: { type: String, default: "1. Goods once sold will not be taken back.\n2. Interest @ 24% p.a. will be charged if payment is delayed." },
    cnTerms: { type: String, default: "1. Subject to verification of physical goods.\n2. Credit will be adjusted in next invoice." },
    dnTerms: { type: String, default: "1. Shortage/Damage claim acknowledged.\n2. Amount debited to your account." },
    invoiceBankVisible: { type: Boolean, default: true },
    cnBankVisible: { type: Boolean, default: false },
    dnBankVisible: { type: Boolean, default: false },
    scrollingMessage: {
        text:  { type: String, default: "Welcome to EMYRIS OMS Portal - Your partner in healthcare." },
        color: { type: String, default: "#6366f1" },
        speed: { type: Number, default: 30 }
    },
    invoiceStyle: { type: String, default: 'classic' }
});

// 2. Global Masters
const categorySchema = new mongoose.Schema({ name: { type: String, required: true, unique: true } });
const groupSchema = new mongoose.Schema({ name: { type: String, required: true, unique: true } });
const hsnSchema = new mongoose.Schema({ code: { type: String, required: true, unique: true }, description: String });
const gstSchema = new mongoose.Schema({ rate: { type: Number, required: true, unique: true } });
const hqSchema = new mongoose.Schema({ name: { type: String, required: true, unique: true }, code: String });

// 2. Product Master
const productSchema = new mongoose.Schema({
    name: { type: String, required: true },
    manufacturer: { type: String, default: "" },
    hsn: String,
    category: { type: String, default: "GENERAL" },
    group: { type: String, default: "GENERAL" },
    packing: String,
    mrp: { type: Number, default: 0 },
    ptr: { type: Number, default: 0 }, // Price to Retailer
    pts: { type: Number, default: 0 }, // Price to Stockist
    gstPercent: { type: Number, default: 12 },
    qtyAvailable: { type: Number, default: 0 },
    bonusScheme: {
        buy: { type: Number, default: 0 },
        get: { type: Number, default: 0 }
    },
    batches: [{
        batchNo: { type: String, required: true },
        mfgDate: { type: String },
        expDate: { type: String },
        mrp: { type: Number, default: 0 },
        pts: { type: Number, default: 0 },
        ptr: { type: Number, default: 0 },
        qtyAvailable: { type: Number, default: 0 }
    }],
    active: { type: Boolean, default: true }
}).index({ name: 1, category: 1, active: 1 }); // Performance index

// 3. Stockist / Distributor
const stockistSchema = new mongoose.Schema({
    name: { type: String, required: true },
    loginId: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    address: String,
    phone: String,
    email: String,
    dlNo: String,
    gstNo: String,
    fssaiNo: String,
    panNo: { type: String, required: true },
    approved: { type: Boolean, default: false },
    negotiatedPrices: [{
        productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        lockedRate: Number,
        expiryDate: Date,
        note: String
    }],
    stockistCode: String,
    loginPin: String,
    registeredAt: { type: Date, default: Date.now },
    partyType: { type: String, enum: ['STOCKIST', 'SUPPLIER'], default: 'STOCKIST' },
    bankName: String,
    bankAccountNo: String,
    bankIfsc: String,
    creditLimit: { type: Number, default: 0 },
    outstandingBalance: { type: Number, default: 0 },
    city: String,
    state: String,
    pincode: String,
    hq: { type: String, default: "" } // Headquarters Assigned
}).index({ loginId: 1, partyType: 1, name: 1 }); // Performance index


// 4. Order
const orderSchema = new mongoose.Schema({
    orderNo: { type: String, unique: true },
    stockist: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist' },
    stockistCode: String,
    items: [{
        product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        manufacturer: String,
        batch: String,
        mfgDate: String,
        expDate: String,
        qty: Number,
        bonusQty: { type: Number, default: 0 },
        priceUsed: Number,
        askingRate: Number,
        masterRate: Number,
        negotiationNote: String,
        totalValue: Number
    }],
    subTotal: Number,
    gstAmount: Number,
    grandTotal: Number,
    status: { type: String, default: 'pending' },
    bonusApproval: {
        isManual: { type: Boolean, default: false },
        approvedBy: String,
        approvedAt: Date
    },
    hq: { type: String, default: "" }, // Captured HQ for this order
    createdAt: { type: Date, default: Date.now }
}).index({ orderNo: 1, status: 1, createdAt: -1 });

// 5. Invoice (Snapshot of Approved Order)
const invoiceSchema = new mongoose.Schema({
    invoiceNo: { type: String, unique: true },
    order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
    stockist: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist' },
    stockistName: String,
    stockistCode: String,
    items: [{
        product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        manufacturer: String,
        hsn: String,
        batch: String,
        mfgDate: String,
        expDate: String,
        qty: Number,
        bonusQty: { type: Number, default: 0 },
        mrp: Number,
        priceUsed: Number,
        gstPercent: Number,
        totalValue: Number
    }],
    subTotal: Number,
    gstAmount: Number,
    grandTotal: Number,
    amountInWords: String,
    hq: String,
    createdAt: { type: Date, default: Date.now }
});

// 6. Purchase Entry (Stock-In)
const purchaseEntrySchema = new mongoose.Schema({
    purchaseNo: { type: String, unique: true },
    supplier: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist' },
    supplierName: { type: String, required: true },
    supplierInvoiceNo: String,
    invoiceDate: Date,
    lrNo: String,
    lrDate: Date,
    transport: String,
    paymentMode: { type: String, enum: ['CASH', 'CREDIT'], default: 'CREDIT' },
    remarks: String,
    items: [{
        product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        manufacturer: String,
        batch: String,
        mfgDate: String,
        expDate: String,
        qty: Number,
        bonusQty: { type: Number, default: 0 },
        purchaseRate: Number,
        gstPercent: Number,
        totalValue: Number
    }],
    subTotal: Number,
    gstAmount: Number,
    grandTotal: Number,
    createdAt: { type: Date, default: Date.now }
});

// 7. Financial Notes (Credit Note / Debit Note)
const financialNoteSchema = new mongoose.Schema({
    noteNo: { type: String, unique: true },
    noteType: { type: String, enum: ['CN', 'DN'], required: true },
    party: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist', required: true },
    partyName: String,
    refInvoiceNo: String,
    refInvoiceDate: String,
    amount: { type: Number, required: true },
    reason: { type: String, required: true },
    description: String,
    // Multi-Item Support
    items: [{
        productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        name: String,
        qty: Number,
        hsn: String,
        batchNo: String,
        expDate: String,
        price: Number,
        gstPercent: Number,
        totalValue: Number
    }],
    subTotal:   Number,
    gstAmount:  Number,
    status: { type: String, enum: ['active','pending','approved','rejected'], default: 'active' },
    createdAt: { type: Date, default: Date.now }
});

// 8. Payments (Cash/Bank entries)
const paymentSchema = new mongoose.Schema({
    paymentNo: { type: String, unique: true },
    party: { type: mongoose.Schema.Types.ObjectId, ref: 'Stockist', required: true },
    partyName: String,
    amount: { type: Number, required: true },
    method: { type: String, enum: ['Cash', 'Bank Transfer', 'Cheque', 'UPI', 'Adjustment'], default: 'Bank Transfer' },
    refNo: String,
    type: { type: String, enum: ['RECEIPT', 'PAYMENT'], required: true }, // RECEIPT (In) from Stockist, PAYMENT (Out) to Supplier
    date: { type: Date, default: Date.now }
});

// 9. Failed Emails Log
const failedEmailSchema = new mongoose.Schema({
    to: String,
    subject: String,
    html: String,
    error: String,
    attempts: { type: Number, default: 0 },
    lastAttempt: { type: Date, default: Date.now }
});

// 10. Expense Categories
const expenseCategorySchema = new mongoose.Schema({
    name: { type: String, required: true, unique: true },
    type: { type: String, enum: ['Direct', 'Indirect'], default: 'Indirect' }
});

// 11. Expenses
const expenseSchema = new mongoose.Schema({
    expenseNo: { type: String, unique: true },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'ExpenseCategory' },
    categoryName: String,
    title: String,
    amount: { type: Number, required: true },
    date: { type: Date, default: Date.now },
    paymentMethod: String,
    refNo: String,
    notes: String
});

const mediaSchema = new mongoose.Schema({
    name: String,
    url: String,
    type: { type: String, enum: ['music', 'video'] },
    createdAt: { type: Date, default: Date.now }
});

const Company = mongoose.model('Company', companySchema);
const Media = mongoose.model('Media', mediaSchema);

const Product = mongoose.model('Product', productSchema);
const Stockist = mongoose.model('Stockist', stockistSchema);
const Order = mongoose.model('Order', orderSchema);
const Category = mongoose.model('Category', categorySchema);
const Group = mongoose.model('Group', groupSchema);
const HSN = mongoose.model('HSN', hsnSchema);
const GST = mongoose.model('GST', gstSchema);
const HQ = mongoose.model('HQ', hqSchema);
const Invoice = mongoose.model('Invoice', invoiceSchema);
const PurchaseEntry = mongoose.model('PurchaseEntry', purchaseEntrySchema);
const FinancialNote = mongoose.model('FinancialNote', financialNoteSchema);
const Payment = mongoose.model('Payment', paymentSchema);
const ExpenseCategory = mongoose.model('ExpenseCategory', expenseCategorySchema);
const Expense = mongoose.model('Expense', expenseSchema);
const FailedEmail = mongoose.model('FailedEmail', failedEmailSchema);


// --- NEGOTIATION ENDPOINTS ---

app.put('/api/admin/orders/:orderId/items/:itemId/negotiate', async (req, res) => {
    const { action } = req.body;
    try {
        const order = await Order.findById(req.params.orderId);
        if (!order) return res.status(404).json({ success: false, message: "Order not found" });

        const item = order.items.id(req.params.itemId);
        if (!item) return res.status(404).json({ success: false, message: "Item not found" });

        const { customRate } = req.body;
        const finalRate = customRate !== undefined ? Number(customRate) : (item.askingRate || item.priceUsed);

        if (action === 'reject') {
            item.priceUsed = item.masterRate;
            item.askingRate = undefined;
        } else if (action === 'onetime') {
            item.priceUsed = finalRate;
        } else {
            item.priceUsed = finalRate;
            let expiry = new Date();
            if (action === 'month') expiry.setMonth(expiry.getMonth() + 1);
            if (action === 'year') expiry.setFullYear(expiry.getFullYear() + 1);

            await Stockist.findByIdAndUpdate(order.stockist, {
                $pull: { negotiatedPrices: { productId: item.product } }
            });
            await Stockist.findByIdAndUpdate(order.stockist, {
                $push: { negotiatedPrices: {
                    productId: item.product,
                    lockedRate: item.priceUsed,
                    expiryDate: expiry,
                    note: item.negotiationNote
                }}
            });
        }

        // --- CRITICAL FIX: Update Item Total Value & Recalculate GST Product-wise ---
        item.totalValue = Number((Number(item.priceUsed || 0) * Number(item.qty || 0)).toFixed(2));

        // Fetch products for all items to get their individual GST rates
        const productIds = order.items.map(i => i.product);
        const products = await Product.find({ _id: { $in: productIds } });
        const productMap = {};
        products.forEach(p => productMap[p._id.toString()] = p);

        let newSubTotal = 0;
        let newGstAmount = 0;

        order.items.forEach(i => {
            const p = productMap[i.product.toString()];
            const rate = p ? (p.gstPercent || 0) : 12; // Fallback to 12 if not found
            const itemValue = i.totalValue || 0;
            newSubTotal += itemValue;
            newGstAmount += Number(((itemValue * rate) / 100).toFixed(2));
        });

        order.subTotal = newSubTotal;
        order.gstAmount = newGstAmount;
        order.grandTotal = Math.round(newSubTotal + newGstAmount);

        await order.save();
        res.json({ success: true, order });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// --- API ENDPOINTS ---

app.get('/api/health', (req, res) => res.json({ status: 'running', database: mongoose.connection.readyState === 1 }));

// Auth & Registration
app.post('/api/stockist/register', async (req, res) => {
    try {
        const { name, password, address, phone, email, dlNo, gstNo, fssaiNo, panNo, city, state, pincode } = req.body;
        
        // Auto-generate Login ID (EMY + Random 6 Digits)
        let loginId;
        let isUnique = false;
        while (!isUnique) {
            loginId = 'EMY' + Math.floor(100000 + Math.random() * 900000);
            const existing = await Stockist.findOne({ loginId });
            if (!existing) isUnique = true;
        }

        const newStockist = new Stockist({ name, loginId, password, address, phone, email, dlNo, gstNo, fssaiNo, panNo, city, state, pincode });

        await newStockist.save();
        console.log(`👤 DB: New Stockist saved -> ${name}`);

        // 1. Send Registration Confirmation to Stockist
        const welcomeEmail = `
            <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background-color: #f1f5f9;">
                <div style="background-color: #ffffff; padding: 40px; border-radius: 24px; max-width: 500px; margin: 0 auto; border: 1px solid #e2e8f0;">
                    <h2 style="color: #6366f1; margin-top: 0;">Registration Received!</h2>
                    <p>Hello <strong>${name}</strong>,</p>
                    <p>Thank you for registering with the EMYRIS Distribution Network. Your application is currently under review by our administration team.</p>
                    <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #e2e8f0;">
                        <p style="margin: 0; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase;">Status</p>
                        <p style="margin: 5px 0 0 0; font-size: 18px; font-weight: 800; color: #f59e0b;">APPROVAL PENDING</p>
                    </div>
                    <p style="font-size: 14px; color: #64748b;">Once your Drug License and compliance data are verified, you will receive another email with your activation details.</p>
                </div>
            </div>
        `;
        console.log(`📧 Sending welcome email to: ${email}`);
        await sendEmail(email, "📦 EMYRIS Registration Received - Approval Pending", welcomeEmail);

        // 2. Send Admin Notification to emyrisbio@gmail.com
        const adminNotifyEmail = `
            <div style="font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 30px; background-color: #f8fafc;">
                <div style="background-color: #ffffff; padding: 40px; border-radius: 24px; border: 1px solid #e2e8f0; max-width: 600px; margin: 0 auto; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);">
                    <h2 style="color: #6366f1; margin-top: 0; font-size: 20px;">🔔 New Stockist Registration</h2>
                    <p style="color: #64748b; font-size: 14px;">A new application has been submitted for the EMYRIS Distribution Network.</p>
                    
                    <div style="background: #f1f5f9; padding: 25px; border-radius: 16px; margin: 25px 0; border: 1px solid #e2e8f0;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 14px; color: #1e293b;">
                            <tr><td style="padding: 8px 0; color: #64748b;">Firm Name:</td><td style="padding: 8px 0; font-weight: 700; text-transform: uppercase;">${name}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">Phone:</td><td style="padding: 8px 0; font-weight: 700;">${phone}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">Email:</td><td style="padding: 8px 0; font-weight: 700;">${email}</td></tr>
                            <tr><td colspan="2"><hr style="border: 0; border-top: 1px solid #cbd5e1; margin: 10px 0;"></td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">GSTIN:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${gstNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">PAN:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${panNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">DL No:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${dlNo}</td></tr>
                            <tr><td style="padding: 8px 0; color: #64748b;">FSSAI:</td><td style="padding: 8px 0; font-weight: 700; font-family: monospace; text-transform: uppercase;">${fssaiNo}</td></tr>
                        </table>
                    </div>
                    
                    <p style="font-size: 14px; color: #475569;">Please log in to the <strong>Admin Command Center</strong> to verify compliance documents and approve this registration.</p>
                    <div style="text-align: center; margin-top: 30px;">
                        <a href="${process.env.PORTAL_URL || 'https://emyris-oms.onrender.com'}/admin.html" style="background-color: #6366f1; color: #ffffff; padding: 12px 24px; border-radius: 12px; text-decoration: none; font-weight: 700; font-size: 14px;">OPEN ADMIN DASHBOARD</a>
                    </div>
                </div>
            </div>
        `;
        console.log(`📧 Sending admin notification to: emyrisbio@gmail.com`);
        await sendEmail("emyrisbio@gmail.com", "🔔 New Stockist Registration: " + name, adminNotifyEmail);

        res.json({ 
            success: true, 
            message: `Registration successful! Please wait for Admin approval.`,
            loginId: loginId,
            password: password
        });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/login', async (req, res) => {
    let { loginId, password } = req.body;
    try {
        if (!loginId || !password) return res.status(400).json({ success: false, message: 'ID and Password are required' });
        
        // Case-insensitive ID lookup
        const user = await Stockist.findOne({ 
            loginId: { $regex: new RegExp(`^${loginId.trim()}$`, 'i') }, 
            password: password.trim() 
        });

        if (!user) return res.status(401).json({ success: false, message: 'Invalid Credentials' });
        if (!user.approved) return res.status(403).json({ success: false, message: 'Account pending approval' });
        
        await sendEmail(user.email, "📦 Login Notification", `Hello ${user.name}, you have successfully logged into your EMYRIS Portal.`);
        console.log(`[LOGIN] Success: ${loginId} (${user.email})`);
        
        res.json({ success: true, user, message: 'Login successful' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/stockist/profile/:id', async (req, res) => {
    try {
        const stockist = await Stockist.findById(req.params.id);
        if (!stockist) return res.status(404).json({ success: false, message: 'Stockist not found' });
        res.json({ success: true, stockist });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/verify-login-pin', async (req, res) => {
    const { loginId, pin } = req.body;
    try {
        const user = await Stockist.findOne({ loginId, loginPin: pin });
        if (!user) return res.status(401).json({ success: false, message: 'Invalid or expired PIN' });
        
        user.loginPin = undefined; // Clear pin
        await user.save();
        console.log(`[PIN] Verified for ${loginId}`);
        res.json({ success: true, user });
    } catch (err) { console.error("[PIN] Error:", err.message); res.status(500).json({ error: err.message }); }
});

app.post('/api/stockist/forgot-id-pw', async (req, res) => {
    let { email } = req.body;
    try {
        if (!email) return res.status(400).json({ success: false, message: 'Email is required' });
        email = email.trim().toLowerCase();
        
        console.log(`[RECOVERY] Searching for: "${email}"`);
        const user = await Stockist.findOne({ email: { $regex: new RegExp(`^${email}$`, 'i') } });
        
        if (!user) {
            console.warn(`[RECOVERY] No user found for: ${email}`);
            return res.status(404).json({ success: false, message: 'No account found with this email address.' });
        }

        const emailContent = `
            <div style="font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 40px; background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); color: #f1f5f9;">
                <div style="background: rgba(30, 41, 59, 0.7); padding: 50px; border-radius: 32px; border: 1px solid rgba(255, 255, 255, 0.1); max-width: 500px; margin: 0 auto; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);">
                    <div style="text-align: center; margin-bottom: 40px;">
                        <h1 style="color: #6366f1; margin: 0; font-size: 28px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase;">EMYRIS BIOLIFESCIENCES</h1>
                        <p style="color: #94a3b8; font-size: 14px; margin-top: 8px; font-weight: 600; letter-spacing: 1px;">SECURE CREDENTIALS RECOVERY</p>
                    </div>
                    
                    <p style="font-size: 16px; line-height: 1.6; color: #cbd5e1;">Hello <strong>${user.name}</strong>,</p>
                    <p style="font-size: 15px; line-height: 1.6; color: #94a3b8;">We received a request to retrieve your account credentials. Please use the details below to securely access your portal:</p>
                    
                    <div style="background: rgba(15, 23, 42, 0.6); padding: 35px; border-radius: 24px; margin: 35px 0; border: 1px solid rgba(255, 255, 255, 0.05); text-align: center;">
                        <div style="margin-bottom: 25px;">
                            <label style="display: block; color: #6366f1; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Login ID</label>
                            <span style="font-family: 'Courier New', monospace; color: #fff; font-size: 24px; font-weight: 800; letter-spacing: 1px;">${user.loginId}</span>
                        </div>
                        <div>
                            <label style="display: block; color: #6366f1; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Password</label>
                            <span style="font-family: 'Courier New', monospace; color: #fff; font-size: 24px; font-weight: 800; letter-spacing: 1px;">${user.password}</span>
                        </div>
                    </div>
                    
                    <div style="text-align: center; margin-top: 40px;">
                        <p style="font-size: 12px; color: #64748b; font-weight: 500;">If you did not request this, please contact support immediately.</p>
                        <hr style="border: 0; border-top: 1px solid rgba(255, 255, 255, 0.05); margin: 25px 0;">
                        <p style="font-size: 11px; color: #475569;">&copy; 2026 EMYRIS OMS • ADVANCED DISTRIBUTION SYSTEM</p>
                    </div>
                </div>
            </div>
        `;
        
        await sendEmail(user.email, "📦 Account Credentials Recovery", emailContent);
        res.json({ success: true, message: 'Login details have been sent to your email.' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/stockist/orders/:orderId/invoice', async (req, res) => {
    try {
        const invoice = await Invoice.findOne({ order: req.params.orderId }).populate('stockist');
        if (!invoice) return res.status(404).json({ success: false, message: 'Invoice not found' });
        res.json({ success: true, invoice });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Login
app.post('/api/admin/login', (req, res) => {
    const { adminId, password } = req.body;
    const correctId = process.env.ADMIN_ID || "EMYRIS";
    const correctPass = process.env.ADMIN_PASSWORD || "1234";

    console.log(`[DEBUG] Login attempt - ID: "${adminId}" (${adminId.length}), Pass: "${password}" (${password.length})`);
    console.log(`[DEBUG] Correct - ID: "${correctId}" (${correctId.length}), Pass: "${correctPass}" (${correctPass.length})`);

    if (adminId.trim() === correctId.trim() && password.trim() === correctPass.trim()) {
        res.json({ success: true });
    } else {
        res.status(401).json({ success: false, message: 'Invalid Admin Credentials' });
    }
});

// Admin: Bulk Add Products
app.post('/api/admin/products/bulk', async (req, res) => {
    try {
        const { products } = req.body;
        if (!Array.isArray(products)) return res.status(400).json({ success: false, message: 'Invalid data' });
        const results = { success: 0, failed: 0, errors: [] };
        for (const p of products) {
            try {
                if (!p.name) { results.failed++; results.errors.push("Missing Product Name"); continue; }
                const newProd = new Product({
                    name: p.name,
                    hsn: p.hsn,
                    category: p.category || "GENERAL",
                    mrp: Number(p.mrp) || 0,
                    ptr: Number(p.ptr) || 0,
                    pts: Number(p.pts) || 0,
                    gstPercent: Number(p.gstPercent) || 12,
                    qtyAvailable: Number(p.qtyAvailable) || 0,
                    bonusScheme: { buy: Number(p.buy) || 0, get: Number(p.get) || 0 }
                });
                await newProd.save();
                results.success++;
            } catch (e) {
                results.failed++;
                results.errors.push(`${p.name || 'Unknown'}: ${e.message}`);
            }
        }
        res.json({ success: true, results });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Single Add Product
app.post('/api/admin/products', async (req, res) => {
    try {
        console.log("[DEBUG] Adding Product:", req.body);
        const newProd = new Product(req.body);
        await newProd.save();
        res.json({ success: true, product: newProd });
    } catch (err) { 
        console.error('❌ Product Save Error:', err.message);
        res.status(500).json({ success: false, error: err.message }); 
    }
});

// Admin: Update Product
app.put('/api/admin/products/:id', async (req, res) => {
    try {
        const product = await Product.findByIdAndUpdate(req.params.id, req.body, { new: true });
        if (!product) return res.status(404).json({ success: false, message: 'Product not found' });
        res.json({ success: true, product });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Delete Product
app.delete('/api/admin/products/:id', async (req, res) => {
    try {
        const product = await Product.findByIdAndDelete(req.params.id);
        if (!product) return res.status(404).json({ success: false, message: 'Product not found' });
        res.json({ success: true });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// --- PARTY / STOCKIST MANAGEMENT ---
app.get('/api/admin/stockists', async (req, res) => {
    try {
        const type = req.query.type;
        const query = type ? { partyType: type } : {};
        const stockists = await Stockist.find(query).sort({ registeredAt: -1 });
        res.json(stockists);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.post('/api/admin/stockists', async (req, res) => {
    try {
        const { name, loginId, password, panNo, partyType, address, phone, email, dlNo, gstNo, fssaiNo, creditLimit, outstandingBalance, city, state } = req.body;
        const newParty = new Stockist({
            name, loginId, password, panNo, partyType: partyType || 'STOCKIST', address, phone, email, dlNo, gstNo, fssaiNo, creditLimit, outstandingBalance, city, state,
            approved: true
        });
        await newParty.save();
        res.json({ success: true, party: newParty });
    } catch (e) { res.status(500).json({ success: false, message: e.message }); }
});

app.put('/api/admin/stockists/:id', async (req, res) => {
    try {
        const updated = await Stockist.findByIdAndUpdate(req.params.id, req.body, { new: true });
        res.json({ success: true, party: updated });
    } catch (e) { res.status(500).json({ success: false, message: e.message }); }
});

// Admin: Delete Individual Stockist
app.delete('/api/admin/stockists/:id', async (req, res) => {
    try {
        await Stockist.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Stockist deleted' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Master Delete All Stockists (Wipes only Stockists)
app.delete('/api/admin/stockists-bulk/all', async (req, res) => {
    try {
        const result = await Stockist.deleteMany({});
        res.json({ success: true, message: `${result.deletedCount} Stockists deleted.` });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Approve Stockist
app.put('/api/admin/stockists/:id/approve', async (req, res) => {
    try {
        const sid = req.params.id;
        console.log(`[ADMIN] Approving stockist: ${sid}`);

        // Update Stockist Status
        const stockist = await Stockist.findByIdAndUpdate(sid, { 
            approved: true
        }, { new: true });

        if (!stockist) {
            console.error(`❌ [ADMIN] Stockist ${sid} not found`);
            return res.status(404).json({ success: false, message: 'Stockist not found' });
        }

        console.log(`✅ [ADMIN] Approved: ${stockist.name}`);

        // 4. Send Confirmation Email
        const emailContent = `
            <div style="font-family: sans-serif; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; max-width: 500px; background-color: #ffffff;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h2 style="color: #10b981; margin: 0;">Account Approved!</h2>
                    <p style="color: #64748b; font-size: 14px;">EMYRIS BIOLIFESCIENCES</p>
                </div>
                
                <p>Hello <strong>${stockist.name}</strong>,</p>
                <p>Your account has been verified and successfully approved by the EMYRIS Admin team.</p>
                
                <div style="background: #f0fdf4; padding: 25px; border-radius: 16px; margin: 25px 0; border: 1px solid #bbf7d0; text-align: center;">
                    <p style="margin: 0 0 10px 0; color: #166534; font-size: 0.8rem; font-weight: 700; text-transform: uppercase;">Your Portal Credentials</p>
                    <div style="margin-bottom: 15px;">
                        <span style="color: #64748b; font-size: 13px;">Login ID:</span><br>
                        <strong style="font-family: monospace; font-size: 1.2rem; color: #10b981;">${stockist.loginId}</strong>
                    </div>
                    <div>
                        <span style="color: #64748b; font-size: 13px;">Password:</span><br>
                        <strong style="font-family: monospace; font-size: 1.2rem; color: #10b981;">${stockist.password}</strong>
                    </div>
                </div>
                
                <p>Access the portal here: <a href="${process.env.PORTAL_URL || 'https://emyris-oms.onrender.com'}" style="color: #6366f1; font-weight: 700; text-decoration: none;">Stockist Portal</a></p>
                
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 0.8rem; color: #64748b; text-align: center;">Welcome to the EMYRIS network. We look forward to a successful partnership.</p>
            </div>
        `;
        await sendEmail(stockist.email, "✅ EMYRIS Account Approved - Portal Access Active", emailContent);

        res.json({ success: true, stockist });
    } catch (err) { 
        console.error("❌ [ADMIN] Approval logic failed:", err.message);
        res.status(500).json({ error: err.message }); 
    }
});

// --- SETTINGS & MASTERS ---

app.get('/api/admin/settings', async (req, res) => {
    let settings = await Company.findOne();
    if (!settings) settings = await Company.create({});
    res.json(settings);
});

// --- MEDIA UPLOAD ENDPOINTS ---

app.post('/api/admin/upload-media', upload.single('media'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ success: false, message: "No file uploaded" });
        
        const type = req.body.type; // 'music' or 'video'
        
        // 1. Upload to Cloudinary (Permanent)
        const result = await cloudinary.uploader.upload(req.file.path, {
            resource_type: type === 'video' ? 'video' : 'auto',
            folder: 'emyris_media'
        });

        // 2. Save to Media Library Database
        const newMedia = new Media({
            name: req.file.originalname,
            url: result.secure_url,
            type: type
        });
        await newMedia.save();

        // 3. Update active settings automatically
        let settings = await Company.findOne();
        if (!settings) settings = new Company();
        if (type === 'music') settings.musicUrl = result.secure_url;
        else if (type === 'video') settings.videoUrl = result.secure_url;
        await settings.save();

        // Cleanup local temp file
        if (fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);

        res.json({ success: true, mediaUrl: result.secure_url, media: newMedia, message: `Uploaded to Cloud Library successfully!` });
    } catch (e) { 
        console.error("Cloud Upload Fail:", e);
        res.status(500).json({ success: false, error: e.message }); 
    }
});

// GET: Fetch all media library items
app.get('/api/admin/media', async (req, res) => {
    try {
        const media = await Media.find().sort({ createdAt: -1 });
        res.json(media);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// DELETE: Remove from media library
app.delete('/api/admin/media/:id', async (req, res) => {
    try {
        await Media.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// Serve uploaded files
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

app.post('/api/admin/settings', async (req, res) => {
    try {
        let settings = await Company.findOne();
        if (!settings) {
            settings = new Company(req.body);
        } else {
            const updateData = { ...req.body };
            // Protection: Don't overwrite existing multimedia assets with empty/missing values
            if (!updateData.logoImage && settings.logoImage) delete updateData.logoImage;
            if (!updateData.signatureImage && settings.signatureImage) delete updateData.signatureImage;
            if (!updateData.musicUrl && settings.musicUrl) delete updateData.musicUrl;
            if (!updateData.videoUrl && settings.videoUrl) delete updateData.videoUrl;
            
            Object.assign(settings, updateData);

        }
        await settings.save();
        res.json({ success: true, settings });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// Category Master
app.get('/api/admin/categories', async (req, res) => res.json(await Category.find()));
app.post('/api/admin/categories', async (req, res) => {
    try {
        const cat = new Category(req.body);
        await cat.save();
        res.json({ success: true, category: cat });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/categories/:id', async (req, res) => {
    await Category.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// Group Master
app.get('/api/admin/groups', async (req, res) => res.json(await Group.find()));
app.post('/api/admin/groups', async (req, res) => {
    try {
        const grp = new Group(req.body);
        await grp.save();
        res.json({ success: true, group: grp });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/groups/:id', async (req, res) => {
    await Group.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// HSN Master
app.get('/api/admin/hsns', async (req, res) => res.json(await HSN.find()));
app.post('/api/admin/hsns', async (req, res) => {
    try {
        const hsn = new HSN(req.body);
        await hsn.save();
        res.json({ success: true, hsn });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/hsns/:id', async (req, res) => {
    await HSN.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// GST Master
app.get('/api/admin/gst', async (req, res) => res.json(await GST.find()));
app.post('/api/admin/gst', async (req, res) => {
    try {
        const gst = new GST(req.body);
        await gst.save();
        res.json({ success: true, gst });
    } catch (e) { res.status(500).json({ error: e.message }); }
});
app.delete('/api/admin/gst/:id', async (req, res) => {
    await GST.findByIdAndDelete(req.params.id);
    res.json({ success: true });
});

// HQ Master
app.get('/api/admin/masters/hq', async (req, res) => {
    try {
        const hqs = await HQ.find();
        res.json(hqs);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/masters/hq', async (req, res) => {
    try {
        const hq = new HQ(req.body);
        await hq.save();
        res.json({ success: true, hq });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.delete('/api/admin/masters/hq/:id', async (req, res) => {
    try {
        await HQ.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});


// Email Recovery Endpoints
app.get('/api/admin/failed-emails', async (req, res) => {
    try {
        const failed = await FailedEmail.find().sort({ lastAttempt: -1 });
        res.json(failed);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/failed-emails/:id/retry', async (req, res) => {
    try {
        const email = await FailedEmail.findById(req.params.id);
        if (!email) return res.status(404).json({ success: false, message: 'Email not found' });
        
        const success = await sendEmail(email.to, email.subject, email.html);
        if (success) {
            await FailedEmail.findByIdAndDelete(req.params.id);
            res.json({ success: true });
        } else {
            res.status(500).json({ success: false, message: 'Retry failed again' });
        }
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.delete('/api/admin/failed-emails/:id', async (req, res) => {
    try {
        await FailedEmail.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// Public Products List
app.get('/api/products', async (req, res) => {
    try {
        const products = await Product.find({ active: true });
        res.json(products);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Orders
app.post('/api/orders/create', async (req, res) => {
    try {
        const { stockistId, stockistCode, items, subTotal, gstAmount, grandTotal } = req.body;
        
        // Generate Order No (EMY-ORD-YYYYMMDD-XXXX)
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await Order.countDocuments();
        const orderNo = `EMY-ORD-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        const stockist = await Stockist.findById(stockistId);
        
        const newOrder = new Order({
            orderNo,
            stockist: stockistId,
            stockistCode,
            items,
            subTotal,
            gstAmount,
            grandTotal,
            hq: stockist ? stockist.hq : "" // Auto-pickup HQ if assigned
        });
        await newOrder.save();

        if (stockist) {
            sendOrderEmails(newOrder, stockist);
        }

        res.json({ success: true, order: newOrder });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/api/admin/orders', async (req, res) => {
    try {
        const orders = await Order.find().populate('stockist').sort({ createdAt: -1 });
        res.json(orders);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.put('/api/admin/orders/:id/reject', async (req, res) => {
    try {
        const order = await Order.findByIdAndUpdate(req.params.id, { status: 'rejected' }, { new: true });
        if (!order) return res.status(404).json({ success: false, message: 'Order not found' });
        res.json({ success: true, order });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Stockist: Get My Orders
app.get('/api/orders/my-orders/:stockistId', async (req, res) => {
    try {
        const orders = await Order.find({ stockist: req.params.stockistId }).sort({ createdAt: -1 });
        res.json(orders);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Admin: Approve Order (with Inventory Deduction)
app.put('/api/admin/orders/:id/approve', async (req, res) => {
    try {
        const { approvedBy, batchSelections, selectedHq } = req.body;
        const order = await Order.findById(req.params.id).populate('stockist');
        
        if (!order) return res.status(404).json({ success: false, message: 'Order not found' });
        if (order.status === 'approved') return res.status(400).json({ success: false, message: 'Order already approved' });

        // --- INVENTORY DEDUCTION LOGIC (MANUAL + FIFO BATCH ALLOCATION) ---
        for (const item of order.items) {
            let totalDeduction = (item.qty || 0) + (item.bonusQty || 0);
            if (totalDeduction > 0) {
                const product = await Product.findById(item.product);
                if (product) {
                    // Update overall stock
                    product.qtyAvailable -= totalDeduction;
                    
                    let batchUsed = 'DEFAULT';
                    let mfgUsed = '';
                    let expUsed = '';

                    const preferredBatchNo = (batchSelections && batchSelections[item._id.toString()]) ? batchSelections[item._id.toString()] : null;

                    // Sort batches: Preferred batch first, then by expiry date (FIFO) roughly
                    product.batches.sort((a, b) => {
                        if (preferredBatchNo) {
                            if (a.batchNo === preferredBatchNo && b.batchNo !== preferredBatchNo) return -1;
                            if (b.batchNo === preferredBatchNo && a.batchNo !== preferredBatchNo) return 1;
                        }
                        return new Date(a.expDate || '2099') - new Date(b.expDate || '2099');
                    });

                    for (let i = 0; i < product.batches.length; i++) {
                        if (totalDeduction <= 0) break;
                        let b = product.batches[i];
                        if (b.qtyAvailable > 0) {
                            if (batchUsed === 'DEFAULT') {
                                batchUsed = b.batchNo;
                                mfgUsed = b.mfgDate;
                                expUsed = b.expDate;
                            }
                            
                            if (b.qtyAvailable >= totalDeduction) {
                                b.qtyAvailable -= totalDeduction;
                                totalDeduction = 0;
                            } else {
                                totalDeduction -= b.qtyAvailable;
                                b.qtyAvailable = 0;
                            }
                        }
                    }

                    // Save allocated batch into order so invoice prints it
                    item.batch = batchUsed;
                    item.mfgDate = mfgUsed;
                    item.expDate = expUsed;

                    await product.save();
                    console.log(`📉 [INVENTORY] Deducted items from batch ${batchUsed} for ${item.name}`);
                }
            }
        }

        order.status = 'approved';
        order.bonusApproval = {
            approvedBy: approvedBy || 'ADMIN',
            approvedAt: new Date()
        };

        // Assign HQ if provided (Mandatory for 1st time, or allows update)
        if (selectedHq) {
            order.hq = selectedHq;
            // Update stockist HQ for future automatic pickup
            if (order.stockist) {
                await Stockist.findByIdAndUpdate(order.stockist._id, { hq: selectedHq });
            }
        }

        await order.save();
        res.json({ success: true, order });
    } catch (err) { 
        console.error("❌ Approval Error:", err.message);
        res.status(500).json({ error: err.message }); 
    }
});

// Admin: Delete Order
app.delete('/api/admin/orders/:id', async (req, res) => {
    try {
        await Order.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: 'Order deleted' });
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// --- INVOICE MODULE ---
app.get('/api/admin/invoices', async (req, res) => {
    try {
        const invoices = await Invoice.find().populate('stockist').sort({ createdAt: -1 });
        res.json(invoices);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/invoices/generate/:orderId', async (req, res) => {
    try {
        const order = await Order.findById(req.params.orderId).populate('stockist');
        if (!order) return res.status(404).json({ success: false, message: "Order not found" });
        if (order.status !== 'approved') return res.status(400).json({ success: false, message: "Only approved orders can be invoiced" });

        // Check if invoice already exists
        const existing = await Invoice.findOne({ order: order._id });
        if (existing) return res.json({ success: true, invoice: existing, message: "Invoice already exists" });

        // Generate Invoice No (EMY-INV-YYYYMMDD-XXXX)
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await Invoice.countDocuments();
        const invoiceNo = `EMY-INV-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        // Fetch products to get GST Snapshot
        const productIds = order.items.map(i => i.product);
        const products = await Product.find({ _id: { $in: productIds } });
        const productMap = {};
        products.forEach(p => productMap[p._id.toString()] = p);

        const invoiceItems = order.items.map(item => {
            const p = productMap[item.product.toString()];
            return {
                product: item.product,
                name: item.name,
                manufacturer: p ? p.manufacturer : '',
                hsn: p ? p.hsn : '',
                batch: item.batch || 'DEFAULT',
                mfgDate: item.mfgDate || '',
                expDate: item.expDate || '',
                qty: item.qty,
                bonusQty: item.bonusQty,
                mrp: p ? p.mrp : 0,
                priceUsed: item.priceUsed,
                gstPercent: p ? (p.gstPercent || 12) : 12,
                totalValue: item.totalValue
            };
        });

        const newInvoice = new Invoice({
            invoiceNo,
            order: order._id,
            stockist: order.stockist._id,
            stockistName: order.stockist.name,
            stockistCode: order.stockistCode,
            items: invoiceItems,
            subTotal: order.subTotal,
            gstAmount: order.gstAmount,
            grandTotal: order.grandTotal,
            hq: order.hq
        });

        await newInvoice.save();
        
        // --- ACCOUNTING UPDATE ---
        // Sales Invoice increases what the stockist owes (Outstanding increases)
        await Stockist.findByIdAndUpdate(order.stockist._id, { $inc: { outstandingBalance: order.grandTotal } });
        
        // Update order status to 'invoiced'
        order.status = 'invoiced';
        await order.save();

        res.json({ success: true, invoice: newInvoice });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// --- PURCHASE ENTRY MODULE ---
app.get('/api/admin/purchase-entries', async (req, res) => {
    try {
        const entries = await PurchaseEntry.find().sort({ createdAt: -1 });
        res.json(entries);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/purchase-entries', async (req, res) => {
    try {
        const { 
            supplier, supplierName, supplierInvoiceNo, invoiceDate, 
            lrNo, lrDate, transport, paymentMode, remarks,
            items, subTotal, gstAmount, grandTotal 
        } = req.body;
        
        // Generate Purchase No
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await PurchaseEntry.countDocuments();
        const purchaseNo = `EMY-PUR-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        const newEntry = new PurchaseEntry({
            purchaseNo,
            supplier,
            supplierName,
            supplierInvoiceNo,
            invoiceDate,
            lrNo,
            lrDate,
            transport,
            paymentMode,
            remarks,
            items,
            subTotal,
            gstAmount,
            grandTotal
        });

        await newEntry.save();

        // --- ACCOUNTING UPDATE ---
        if (supplier) {
            // Purchase is a Credit (increases what we owe, decreases "Outstanding" if we use Debit-Credit)
            await Stockist.findByIdAndUpdate(supplier, { $inc: { outstandingBalance: -grandTotal } });
        }
        
        // --- INVENTORY INCREMENT LOGIC (WITH BATCHES) ---
        for (const item of items) {
            const totalIncrement = (item.qty || 0) + (item.bonusQty || 0);
            if (totalIncrement > 0) {
                const product = await Product.findById(item.product);
                if (product) {
                    // 1. Update overall stock
                    product.qtyAvailable += totalIncrement;
                    
                    // 2. Process Batch
                    const targetBatchNo = item.batch || 'DEFAULT';
                    const batchIndex = product.batches.findIndex(b => b.batchNo === targetBatchNo);
                    if (batchIndex > -1) {
                        product.batches[batchIndex].qtyAvailable += totalIncrement;
                    } else {
                        product.batches.push({
                            batchNo: targetBatchNo,
                            mfgDate: item.mfgDate,
                            expDate: item.expDate,
                            qtyAvailable: totalIncrement,
                            ptr: item.purchaseRate || product.ptr || 0,
                            mrp: product.mrp || 0,
                            pts: product.pts || 0
                        });
                    }
                    await product.save();
                }
            }
        }

        res.json({ success: true, entry: newEntry });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.put('/api/admin/purchase-entries/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const { 
            supplier, supplierName, supplierInvoiceNo, invoiceDate, 
            lrNo, lrDate, transport, paymentMode, remarks,
            items, subTotal, gstAmount, grandTotal 
        } = req.body;

        const oldEntry = await PurchaseEntry.findById(id);
        if(!oldEntry) return res.status(404).json({ success: false, message: 'Record not found' });

        // 1. Reverse old inventory
        for(const item of oldEntry.items) {
            const totalDecrement = (item.qty || 0) + (item.bonusQty || 0);
            await Product.findByIdAndUpdate(item.product, { $inc: { qtyAvailable: -totalDecrement } });
        }

        // 2. Reverse old accounting
        if(oldEntry.supplier) {
            await Stockist.findByIdAndUpdate(oldEntry.supplier, { $inc: { outstandingBalance: oldEntry.grandTotal } });
        }

        // 3. Update entry fields (except purchaseNo)
        oldEntry.supplier = supplier;
        oldEntry.supplierName = supplierName;
        oldEntry.supplierInvoiceNo = supplierInvoiceNo;
        oldEntry.invoiceDate = invoiceDate;
        oldEntry.lrNo = lrNo;
        oldEntry.lrDate = lrDate;
        oldEntry.transport = transport;
        oldEntry.paymentMode = paymentMode;
        oldEntry.remarks = remarks;
        oldEntry.items = items;
        oldEntry.subTotal = subTotal;
        oldEntry.gstAmount = gstAmount;
        oldEntry.grandTotal = grandTotal;
        
        await oldEntry.save();

        // 4. Apply new inventory
        for(const item of items) {
            const totalIncrement = (item.qty || 0) + (item.bonusQty || 0);
            await Product.findByIdAndUpdate(item.product, { $inc: { qtyAvailable: totalIncrement } });
        }

        // 5. Apply new accounting
        if(supplier) {
            await Stockist.findByIdAndUpdate(supplier, { $inc: { outstandingBalance: -grandTotal } });
        }

        res.json({ success: true, message: 'Purchase entry updated successfully' });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// --- FINANCIAL NOTES MODULE ---
app.get('/api/admin/financial-notes', async (req, res) => {
    try {
        const notes = await FinancialNote.find().populate('party').sort({ createdAt: -1 });
        res.json(notes);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/financial-notes', async (req, res) => {
    try {
        const { noteType, party, amount, reason, description, refInvoiceNo, refInvoiceDate, items, subTotal, gstAmount } = req.body;
        
        // Generate Note No — unique series per module
        const reasonNoteMap = {
            'Salable Return':   { prefix: 'S-CN',  type: 'CN' },
            'Exp/Brk/Damg CN':  { prefix: 'EB-CN', type: 'CN' },
            'Price Diff CN':    { prefix: 'PD-CN', type: 'CN' },
            'Purchase Return':  { prefix: 'P-DN',  type: 'DN' },
            'Price Diff DN':    { prefix: 'PD-DN', type: 'DN' },
            'Brk/Dmg/Loss DN':  { prefix: 'BD-DN', type: 'DN' }
        };
        const noteMap = reasonNoteMap[reason] || { prefix: `EMY-${noteType}`, type: noteType };
        const count = await FinancialNote.countDocuments({ reason });
        const dateStr = new Date().toISOString().slice(0,10).replace(/-/g,'');
        const noteNo = `${noteMap.prefix}-${dateStr}-${(count+1).toString().padStart(4,'0')}`;

        const partyObj = await Stockist.findById(party);
        
        const newNote = new FinancialNote({
            noteNo, noteType, party,
            partyName: partyObj ? partyObj.name : 'Unknown',
            amount, reason, description, refInvoiceNo, refInvoiceDate, items,
            subTotal, gstAmount
        });

        // ── PDCN QUANTITY VALIDATION (Admin Side) ──
        if (reason === 'Price Diff CN' && items && items.length) {
            const invoices = await Invoice.find({ stockist: party, status: { $in: ['invoiced','approved'] } });
            const billedMap = {};
            for (const inv of invoices) {
                for (const item of (inv.items || [])) {
                    const pid = String(item.productId || '');
                    if (pid) billedMap[pid] = (billedMap[pid] || 0) + (item.qty || 0);
                }
            }
            for (const item of items) {
                const pid = String(item.productId);
                const billed = billedMap[pid] || 0;
                if (item.qty > billed) {
                    return res.status(400).json({ success: false, error: `QUANTITY ERROR: Product "${item.name}" was only billed ${billed} units total. Cannot raise PDCN for ${item.qty} units.` });
                }
            }
        }

        // ── INVENTORY LOGIC (Only for inventory-affecting reasons) ────────────
        // Salable Return  → add back to stock (goods returned in salable condition)
        // Purchase Return → deduct from stock (goods sent back to supplier)
        // ALL OTHERS (Exp/Brk/Damg CN, Price Diff CN, Price Diff DN, Brk/Dmg/Loss DN)
        //              → LEDGER ONLY, zero inventory touch
        const inventoryAdj = (r) => {
            if (r === 'Salable Return')  return +1;
            if (r === 'Purchase Return') return -1;
            return 0; // ledger-only
        };
        const adjFactor = inventoryAdj(reason);

        if (adjFactor !== 0 && items && Array.isArray(items)) {
            for (const item of items) {
                const product = await Product.findById(item.productId);
                if (product) {
                    const adj = adjFactor * item.qty;
                    product.qtyAvailable += adj;
                    if (item.batchNo) {
                        const bIdx = product.batches.findIndex(b => b.batchNo === item.batchNo);
                        if (bIdx > -1) {
                            product.batches[bIdx].qtyAvailable += adj;
                        } else if (adj > 0) {
                            product.batches.push({
                                batchNo: item.batchNo,
                                expDate: item.expDate || 'N/A',
                                qtyAvailable: adj,
                                mrp: item.price || 0
                            });
                        }
                    }
                    await product.save();
                }
            }
        }

        await newNote.save();

        if (partyObj) {
            const adjustment = noteType === 'CN' ? -amount : amount;
            await Stockist.findByIdAndUpdate(party, { $inc: { outstandingBalance: adjustment } });
        }

        res.json({ success: true, note: newNote });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.put('/api/admin/financial-notes/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const { noteType, party, amount, reason, description, refInvoiceNo, refInvoiceDate, items, subTotal, gstAmount } = req.body;
        
        const oldNote = await FinancialNote.findById(id);
        if (!oldNote) return res.status(404).json({ success: false, message: "Note not found" });

        // 1. REVERSE OLD LOGIC
        // Reverse Accounting impact on Stockist balance
        const oldParty = await Stockist.findById(oldNote.party);
        if (oldParty) {
            const oldAdj = oldNote.noteType === 'CN' ? oldNote.amount : -oldNote.amount; 
            await Stockist.findByIdAndUpdate(oldNote.party, { $inc: { outstandingBalance: oldAdj } });
        }

        // Reverse Inventory (only for inventory-affecting reasons)
        const oldAdjFactor = (() => {
            if (oldNote.reason === 'Salable Return')  return -1; // reverse: remove what was added
            if (oldNote.reason === 'Purchase Return') return +1; // reverse: restore what was removed
            return 0;
        })();
        if (oldAdjFactor !== 0 && oldNote.items && Array.isArray(oldNote.items)) {
            for (const item of oldNote.items) {
                const product = await Product.findById(item.productId);
                if (product) {
                    const adj = oldAdjFactor * item.qty;
                    product.qtyAvailable += adj;
                    if (item.batchNo) {
                        const bIdx = product.batches.findIndex(b => b.batchNo === item.batchNo);
                        if (bIdx > -1) product.batches[bIdx].qtyAvailable += adj;
                    }
                    await product.save();
                }
            }
        }

        // 2. APPLY NEW LOGIC
        const partyObj = await Stockist.findById(party);
        
        // ── PDCN QUANTITY VALIDATION (Admin Side Update) ──
        if (reason === 'Price Diff CN' && items && items.length) {
            const invoices = await Invoice.find({ stockist: party, status: { $in: ['invoiced','approved'] } });
            const billedMap = {};
            for (const inv of invoices) {
                for (const item of (inv.items || [])) {
                    const pid = String(item.productId || '');
                    if (pid) billedMap[pid] = (billedMap[pid] || 0) + (item.qty || 0);
                }
            }
            for (const item of items) {
                const pid = String(item.productId);
                const billed = billedMap[pid] || 0;
                if (item.qty > billed) {
                    return res.status(400).json({ success: false, error: `QUANTITY ERROR: Product "${item.name}" was only billed ${billed} units total. Cannot raise PDCN for ${item.qty} units.` });
                }
            }
        }

        oldNote.noteType = noteType;
        oldNote.party = party;
        oldNote.partyName = partyObj ? partyObj.name : 'Unknown';
        oldNote.amount = amount;
        oldNote.reason = reason;
        oldNote.description = description;
        oldNote.refInvoiceNo = refInvoiceNo;
        oldNote.refInvoiceDate = refInvoiceDate;
        oldNote.items = items;
        oldNote.subTotal = subTotal;
        oldNote.gstAmount = gstAmount;

        // Apply New Accounting
        if (partyObj) {
            const newAdj = noteType === 'CN' ? -amount : amount;
            await Stockist.findByIdAndUpdate(party, { $inc: { outstandingBalance: newAdj } });
        }

        // Apply New Inventory (only for inventory-affecting reasons)
        const newAdjFactor = (() => {
            if (reason === 'Salable Return')  return +1;
            if (reason === 'Purchase Return') return -1;
            return 0;
        })();
        if (newAdjFactor !== 0 && items && Array.isArray(items)) {
            for (const item of items) {
                const product = await Product.findById(item.productId);
                if (product) {
                    const adj = newAdjFactor * item.qty;
                    product.qtyAvailable += adj;
                    if (item.batchNo) {
                        const bIdx = product.batches.findIndex(b => b.batchNo === item.batchNo);
                        if (bIdx > -1) {
                            product.batches[bIdx].qtyAvailable += adj;
                        } else if (adj > 0) {
                            product.batches.push({ batchNo: item.batchNo, expDate: item.expDate || 'N/A', qtyAvailable: adj, mrp: item.price || 0 });
                        }
                    }
                    await product.save();
                }
            }
        }

        await oldNote.save();
        res.json({ success: true, note: oldNote });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.delete('/api/admin/financial-notes/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const note = await FinancialNote.findById(id);
        if (!note) return res.status(404).json({ success: false, message: "Note not found" });

        // REVERSE LOGIC
        // Reverse Accounting impact
        const party = await Stockist.findById(note.party);
        if (party) {
            const adj = note.noteType === 'CN' ? note.amount : -note.amount; 
            await Stockist.findByIdAndUpdate(note.party, { $inc: { outstandingBalance: adj } });
        }

        // Reverse Inventory on delete (only for inventory-affecting reasons)
        const delAdjFactor = (() => {
            if (note.reason === 'Salable Return')  return -1;
            if (note.reason === 'Purchase Return') return +1;
            return 0;
        })();
        if (delAdjFactor !== 0 && note.items && Array.isArray(note.items)) {
            for (const item of note.items) {
                const product = await Product.findById(item.productId);
                if (product) {
                    const adj = delAdjFactor * item.qty;
                    product.qtyAvailable += adj;
                    if (item.batchNo) {
                        const bIdx = product.batches.findIndex(b => b.batchNo === item.batchNo);
                        if (bIdx > -1) product.batches[bIdx].qtyAvailable += adj;
                    }
                    await product.save();
                }
            }
        }

        await FinancialNote.findByIdAndDelete(id);
        res.json({ success: true, message: "Note deleted and impacts reversed." });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});


// --- PRICE DIFF CN (PDCN) INTELLIGENCE APIs ---

// GET: Fetch per-product billed qty and already-claimed qty for a party
// Used for real-time eligibility validation in the PDCN form
app.get('/api/admin/pdcn/eligibility/:partyId', async (req, res) => {
    try {
        const { partyId } = req.params;

        // Aggregate all invoiced items for this party
        const invoices = await Invoice.find({ stockist: partyId, status: { $in: ['invoiced','approved'] } })
            .select('items');

        const billedMap = {}; // productId -> { name, totalBilledQty, invoices: [{invoiceNo, qty, price, batch}] }
        for (const inv of invoices) {
            for (const item of (inv.items || [])) {
                const pid = String(item.productId || item._id || '');
                if (!pid) continue;
                if (!billedMap[pid]) {
                    billedMap[pid] = { name: item.name, totalBilledQty: 0, invoices: [] };
                }
                billedMap[pid].totalBilledQty += (item.qty || 0);
                billedMap[pid].invoices.push({ qty: item.qty, price: item.priceUsed || item.price, batch: item.batch });
            }
        }

        // Aggregate already-claimed PDCN qty for this party
        const claimedNotes = await FinancialNote.find({ party: partyId, reason: 'Price Diff CN' })
            .select('items status');
        const claimedMap = {}; // productId -> totalClaimedQty (approved + pending)
        for (const note of claimedNotes) {
            if (note.status === 'rejected') continue; // rejected claims don't count
            for (const item of (note.items || [])) {
                const pid = String(item.productId || '');
                if (!pid) continue;
                claimedMap[pid] = (claimedMap[pid] || 0) + (item.qty || 0);
            }
        }

        // Build response with eligible qty
        const eligibility = {};
        for (const [pid, data] of Object.entries(billedMap)) {
            const claimed = claimedMap[pid] || 0;
            eligibility[pid] = {
                name: data.name,
                totalBilledQty:  data.totalBilledQty,
                totalClaimedQty: claimed,
                eligibleQty:     Math.max(0, data.totalBilledQty - claimed),
            };
        }

        res.json({ success: true, eligibility });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// POST: Stockist self-service PDCN claim submission
// Accessible via /pdcn-portal endpoint (stockist logs in with their credentials)
app.post('/api/stockist/pdcn-claim', async (req, res) => {
    try {
        const { stockistId, items, refInvoiceNo, refInvoiceDate } = req.body;
        if (!stockistId || !items || !items.length) return res.status(400).json({ success: false, error: 'Party and items are required.' });

        const partyObj = await Stockist.findById(stockistId);
        if (!partyObj) return res.status(404).json({ success: false, error: 'Party not found.' });

        // Eligibility check per item
        const invoices = await Invoice.find({ stockist: stockistId, status: { $in: ['invoiced','approved'] } });
        const billedMap = {};
        for (const inv of invoices) {
            for (const item of (inv.items || [])) {
                const pid = String(item.productId || '');
                if (!pid) continue;
                billedMap[pid] = (billedMap[pid] || 0) + (item.qty || 0);
            }
        }
        const claimedNotes = await FinancialNote.find({ party: stockistId, reason: 'Price Diff CN', status: { $ne: 'rejected' } });
        const claimedMap = {};
        for (const note of claimedNotes) {
            for (const item of (note.items || [])) {
                const pid = String(item.productId || '');
                claimedMap[pid] = (claimedMap[pid] || 0) + (item.qty || 0);
            }
        }

        for (const item of items) {
            const pid = String(item.productId);
            const billed  = billedMap[pid] || 0;
            const claimed = claimedMap[pid] || 0;
            const eligible = Math.max(0, billed - claimed);
            if (item.qty > eligible) {
                return res.status(400).json({
                    success: false,
                    error: `Product "${item.name}": You have claimed ${claimed} of ${billed} billed units. Only ${eligible} units are eligible for PDCN. Cannot claim ${item.qty}.`
                });
            }
        }

        const count = await FinancialNote.countDocuments({ reason: 'Price Diff CN' });
        const dateStr = new Date().toISOString().slice(0,10).replace(/-/g,'');
        const noteNo  = `PD-CN-${dateStr}-${(count+1).toString().padStart(4,'0')}`;

        const subTotal  = items.reduce((s, i) => s + (i.qty * i.priceDiff), 0);
        const gstAmount = items.reduce((s, i) => s + (i.qty * i.priceDiff * (i.gstPercent||0) / 100), 0);
        const amount    = Math.round(subTotal + gstAmount);

        const claim = new FinancialNote({
            noteNo, noteType: 'CN', party: stockistId,
            partyName: partyObj.name,
            amount, subTotal, gstAmount,
            reason: 'Price Diff CN',
            status: 'pending',  // Needs admin approval
            description: `PDCN self-claim against Inv: ${refInvoiceNo || 'N/A'}`,
            refInvoiceNo, refInvoiceDate,
            items: items.map(i => ({
                productId: i.productId, name: i.name,
                qty: i.qty, price: i.priceDiff,
                gstPercent: i.gstPercent || 0,
                totalValue: i.qty * i.priceDiff * (1 + (i.gstPercent||0)/100),
                batchNo: i.batchNo, expDate: i.expDate, hsn: i.hsn
            }))
        });
        await claim.save();

        res.json({ success: true, noteNo, message: 'Your PDCN claim has been submitted for admin approval.' });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// POST: Admin approve/reject PDCN claim
app.post('/api/admin/pdcn-claim/:id/review', async (req, res) => {
    try {
        const { id } = req.params;
        const { action } = req.body; // 'approve' or 'reject'
        const note = await FinancialNote.findById(id);
        if (!note || note.reason !== 'Price Diff CN') return res.status(404).json({ success: false });

        if (action === 'approve') {
            note.status = 'approved';
            await note.save();
            // Apply ledger impact (no inventory)
            const adj = -note.amount; // CN reduces outstanding
            await Stockist.findByIdAndUpdate(note.party, { $inc: { outstandingBalance: adj } });
            res.json({ success: true, message: 'PDCN Claim approved. CN issued to party ledger.' });
        } else {
            note.status = 'rejected';
            await note.save();
            res.json({ success: true, message: 'PDCN Claim rejected.' });
        }
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// Serve PDCN Self-Service Portal


app.get('/pdcn-portal', (req, res) => {
    res.sendFile(path.join(__dirname, 'pdcn-portal.html'));
});

// GET: Fetch notes for a specific stockist (for portal history)
app.get('/api/stockist/notes', async (req, res) => {
    try {
        const { partyId, reason } = req.query;
        const filter = { party: partyId };
        if (reason) filter.reason = reason;
        const notes = await FinancialNote.find(filter).sort({ createdAt: -1 });
        res.json(notes);
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

// --- PAYMENTS & LEDGER MODULE ---

app.get('/api/admin/payments', async (req, res) => {
    try {
        const payments = await Payment.find().populate('party').sort({ date: -1 });
        res.json(payments);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/payments', async (req, res) => {
    try {
        const { party, amount, method, refNo, type, date } = req.body;
        
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await Payment.countDocuments({ type });
        const paymentNo = `PAY-${type === 'RECEIPT' ? 'REC' : 'OUT'}-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        const partyObj = await Stockist.findById(party);
        const newPayment = new Payment({
            paymentNo, party, partyName: partyObj ? partyObj.name : 'Unknown',
            amount, method, refNo, type, date: date || new Date()
        });
        await newPayment.save();

        // Update Balance
        if (partyObj) {
            // Receipt from Stockist decreases what they owe (Outstanding decreases)
            // Payment to Supplier decreases what we owe them (Negative balance moves towards zero)
            const adjustment = type === 'RECEIPT' ? -amount : amount; 
            await Stockist.findByIdAndUpdate(party, { $inc: { outstandingBalance: adjustment } });
        }

        res.json({ success: true, payment: newPayment });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.delete('/api/admin/payments/:id', async (req, res) => {
    try {
        await Payment.findByIdAndDelete(req.params.id);
        res.json({ success: true, message: "Payment deleted" });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// --- EXPENSE MODULE ---

app.get('/api/admin/expenseCategories', async (req, res) => {
    try {
        const cats = await ExpenseCategory.find();
        res.json(cats);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/expenseCategories', async (req, res) => {
    try {
        const newCat = new ExpenseCategory(req.body);
        await newCat.save();
        res.json({ success: true, category: newCat });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.delete('/api/admin/expenseCategories/:id', async (req, res) => {
    try {
        await ExpenseCategory.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/admin/expenses', async (req, res) => {
    try {
        const expenses = await Expense.find().populate('category').sort({ date: -1 });
        res.json(expenses);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/admin/expenses', async (req, res) => {
    try {
        const { category, title, amount, date, paymentMethod, refNo, notes } = req.body;
        const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
        const count = await Expense.countDocuments();
        const expenseNo = `EXP-${dateStr}-${(count + 1).toString().padStart(4, '0')}`;

        const catObj = await ExpenseCategory.findById(category);
        const newExp = new Expense({
            expenseNo, category, categoryName: catObj ? catObj.name : 'Uncategorized',
            title, amount, date: date || new Date(), paymentMethod, refNo, notes
        });
        await newExp.save();
        res.json({ success: true, expense: newExp });
    } catch (e) { res.status(500).json({ success: false, error: e.message }); }
});

app.delete('/api/admin/expenses/:id', async (req, res) => {
    try {
        await Expense.findByIdAndDelete(req.params.id);
        res.json({ success: true });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// --- ADVANCED REPORTING AGGREGATOR ---

app.get('/api/admin/reports/full-audit', async (req, res) => {
    try {
        const [invoices, purchases, payments, notes, expenses, products, stockists] = await Promise.all([
            Invoice.find().populate('stockist'),
            PurchaseEntry.find(),
            Payment.find().populate('party'),
            FinancialNote.find().populate('party'),
            Expense.find().populate('category'),
            Product.find(),
            Stockist.find()
        ]);
        res.json({
            invoices, purchases, payments, notes, expenses, products, stockists,
            timestamp: new Date()
        });
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/api/admin/parties/:id/ledger', async (req, res) => {
    try {
        const partyId = req.params.id;
        
        // Fetch all related transactions
        const [invoices, purchases, notes, payments] = await Promise.all([
            Invoice.find({ stockist: partyId }),
            PurchaseEntry.find({ supplier: partyId }), 
            FinancialNote.find({ party: partyId }),
            Payment.find({ party: partyId })
        ]);

        // Standardize entries
        const ledger = [];

        invoices.forEach(i => ledger.push({
            date: i.createdAt,
            refNo: i.invoiceNo,
            type: 'INVOICE',
            description: 'Sales Invoice',
            debit: i.grandTotal,
            credit: 0
        }));

        purchases.forEach(p => ledger.push({
            date: p.createdAt,
            refNo: p.purchaseNo,
            type: 'PURCHASE',
            description: `Supplier Inv: ${p.supplierInvoiceNo}`,
            debit: 0,
            credit: p.grandTotal
        }));

        notes.forEach(n => ledger.push({
            date: n.createdAt,
            refNo: n.noteNo,
            type: n.noteType === 'CN' ? 'CREDIT NOTE' : 'DEBIT NOTE',
            description: n.reason,
            debit: n.noteType === 'DN' ? n.amount : 0,
            credit: n.noteType === 'CN' ? n.amount : 0
        }));

        payments.forEach(p => ledger.push({
            date: p.date,
            refNo: p.paymentNo,
            type: p.type,
            description: `${p.method} - Ref: ${p.refNo || 'N/A'}`,
            debit: 0,
            credit: p.amount // Payment/Receipt always credits the account (reduces debt)
        }));

        // Sort by date
        ledger.sort((a, b) => new Date(a.date) - new Date(b.date));

        res.json(ledger);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

// --- REPORTING MODULE ---

app.get('/api/admin/reports/gstr1', async (req, res) => {
    try {
        const { month, year } = req.query;
        if (!month || !year) return res.status(400).json({ error: "Month and Year required" });

        const startDate = new Date(year, month - 1, 1);
        const endDate = new Date(year, month, 0, 23, 59, 59);

        const invoices = await Invoice.find({
            createdAt: { $gte: startDate, $lte: endDate }
        }).populate('stockist');

        // GSTR-1 B2B Schema: GSTIN, Party Name, Invoice No, Date, Value, Rate, Taxable Value, IGST, CGST, SGST
        const report = invoices.map(inv => {
            const party = inv.stockist;
            const taxableValue = inv.subTotal;
            const taxRate = 12; // Default for now, or derive from items
            
            // In a real ERP, we'd split CGST/SGST vs IGST based on State.
            // For now, let's provide a summary.
            return {
                "GSTIN of Recipient": party ? party.gstNo : "N/A",
                "Receiver Name": inv.stockistName,
                "Invoice Number": inv.invoiceNo,
                "Invoice Date": new Date(inv.createdAt).toLocaleDateString('en-GB'),
                "Invoice Value": inv.grandTotal,
                "Place of Supply": party ? party.state : "N/A",
                "Reverse Charge": "N",
                "Invoice Type": "Regular",
                "Rate": taxRate,
                "Taxable Value": taxableValue,
                "Integrated Tax": party && party.state !== "TELANGANA" ? inv.gstAmount : 0, // Simplified logic
                "Central Tax": party && party.state === "TELANGANA" ? inv.gstAmount / 2 : 0,
                "State/UT Tax": party && party.state === "TELANGANA" ? inv.gstAmount / 2 : 0,
                "Cess": 0
            };
        });

        res.json(report);
    } catch (e) { res.status(500).json({ error: e.message }); }
});

app.listen(PORT, () => console.log(`🚀 OMS Server running on http://localhost:${PORT}`));
